bluerobotics/cockpit

public/images/LogitechExtreme3DPro.svg
src/assets/joystick-profiles.ts
src/components/joysticks/JoystickPS.vue
src/libs/joystick/manager.ts
src/types/joystick.ts
src/views/ConfigurationJoystickView.vue

https://github.com/bluerobotics/cockpit/assets/6551040/2fa0e615-5fa8-4ae8-ba6c-7eb96274681c
There's a lot to improve, like supporting the rotation of the central stick (5th axis) with the correspondent rotation of the buttons attached to it, but this is a starter that makes the life of those with this kind of joystick much easier.
~I'm waiting for feedback from the Symbytech team, so we can also have the default mapping for this joystick, before opening for review.~ Symbytech team confirmed it's working correctly.

Add first flight joystick (Logitech Extreme 3D Pro)

---

src/components/mini-widgets/MiniVideoRecorder.vue
src/components/widgets/VideoPlayer.vue
src/composables/webRTC.ts
src/libs/utils.ts
src/libs/webrtc/session.ts
src/stores/video.ts
src/views/ConfigurationGeneralView.vue

This patch allows the user to select which IPs should be allowed to transmit WebRTC video streams.
The selection is persistent between boots.
The only thing missing now is a popup saying to the user that he should define those (when they are undefined).
The solution was developed by @joaoantoniocardoso at #564. I kept his commits and polished the solution from there.
Fix #526 
https://github.com/bluerobotics/cockpit/assets/6551040/86124b93-37ef-48db-b0a6-8954ea2ef74a

Allow blocking IPs from transmitting WebRTC video

---

src/assets/altitude-icon.svg
src/components/MiniWidgetInstantiator.vue
src/components/mini-widgets/RelativeAltitudeIndicator.vue
src/libs/vehicle/ardupilot/ardupilot.ts
src/libs/vehicle/types.ts
src/types/miniWidgets.ts

Adding a mini widget to show the relative altitude of vehicles. This is particularly helpful for air vehicles.

Add Relative Altitude Mini Widget

---

src/libs/vehicle/ardupilot/arducopter.ts
src/libs/vehicle/ardupilot/arduplane.ts
src/stores/mainVehicle.ts

This Merge Request to fix the mode selector not showing the current mode as described here 
https://github.com/bluerobotics/cockpit/issues/574
Makes the mode be driven off of the custom_mode field in the heartbeat.

Update Mode for Copter and Plane Vehicle Types

---

src/components/EditMenu.vue
src/libs/blueos.ts
src/stores/widgetManager.ts

Allow saving widget profiles on the vehicle

---

src/components/mini-widgets/VeryGenericIndicator.vue

This is a deprecated code from when this mini-widget was configured by clicking in it.

Remove button-like behavior from `VeryGenericIndicator`

---

README.md

It was reported by @DonLakeFlyer that `bun`, when installed from Snap, has not been able to install the repository libraries.

Improve README with instructions on installing `bun` and the backend providers

---

src/components/widgets/VideoPlayer.vue
src/stores/video.ts

Warn user when multiple IP routes are being used for the WebRTC streaming

---

src/components/mini-widgets/DepthIndicator.vue

https://github.com/bluerobotics/cockpit/assets/6551040/71e9ffc8-27aa-4509-a185-367ccb711a90
This way it provides the indication in a sane matter, without extra unnecessary precision and without breaking the UI.
(Actually) fix #376

Adjust `DepthIndicator` precision based on it's value (and fix it's width)

---

src/components/mini-widgets/DepthIndicator.vue

This kind of problem was happening for really small values:
We now support only values of 1cm or more.
Thanks @joaoantoniocardoso for quickly reporting this one.

Fix `DepthIndicator` for smaller (<10cm) and residual (<1cm) values

---

src/assets/defaults.ts
src/components/mini-widgets/VeryGenericIndicator.vue
src/types/genericIndicator.ts

This problem was happening for smaller screens.
Before:
After:

Fix generic indicator size

---

src/stores/controller.ts
src/views/ConfigurationJoystickView.vue

Those are minor UI improvements and/or fixes requested during our last software meeting that did not enter #553.

Minor UI improvements joystick map

---

src/stores/controller.ts
src/stores/widgetManager.ts
src/views/ConfigurationJoystickView.vue

And with this last one merged, we finish [the BETA milestone](https://github.com/bluerobotics/cockpit/milestone/1).
To be merged after #629.
Fix #556.

Sync joystick mapping and functions mapping with vehicle

---

src/assets/defaults.ts

defaults: Use hostname for checking development build, instead of NODE_ENV

---

src/libs/vehicle/ardupilot/types.ts
src/types/mission.ts
src/views/MissionPlanningView.vue

Internally they were always being converted to the regular "Pass-by" type

mission-planning: Remove unused "Takeoff" and "Land" waypoint types

---

src/App.vue

mision-name: Don't wrap text on shrinked screens

---

src/components/widgets/Map.vue
src/libs/vehicle/ardupilot/ardupilot.ts
src/stores/mainVehicle.ts

This merge request adds the ability to command to goto a point by clicking on the map widget.

Goto Point on Map Click

---

src/components/ConfigurationMenu.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/components/widgets/VideoPlayer.vue
src/composables/webRTC.ts
src/libs/sensors-logging.ts
src/libs/webrtc/signaller.ts
src/stores/video.ts
src/types/video.ts
src/views/ConfigurationVideoView.vue

With this patch, the video store begins being responsible for internally routing available video streams.
https://github.com/bluerobotics/cockpit/assets/6551040/be61243d-39dc-4de6-8e53-915247cabdf7
Instead of having each video stream consumer (e.g.: VideoPlayer, MiniVideoRecorder) taking full control of the stream it is consuming, we delegate that to the video store, with the widget solely requesting (to the store) the stream it needs. The video store them checks if the requested stream is already being consumed, and if so, routes the same stream, instead of opening a new one with the WebRTC server, which was causing unnecessary usage of both bandwidth and computer resources, to the point of causing system failures or video stuttering.
In resume, with this patch one can add as many …

Video store rules all

---

src/components/mini-widgets/MiniVideoRecorder.vue
src/stores/video.ts
src/types/video.ts

Put the video store in charge of managing the video recordings, so recording information gets stored with the stream data. There are two main benefits on this:
- The lifecycle of a widget (e.g.: a view being changed and a recording widget being unmounted) does not affect the state of a recording
- Multiple recordings, from different streams, can be done simultaneously
Fix #624 
Fix #633
~To be merged after #654.~

Improve video recording management

---

src/libs/blueos.ts
src/stores/video.ts

Fix #659.
~To be merged after #655.~

Automatically set ice ips

---

src/components/EditMenu.vue

Fixes #597
**Use the variable name as the widget name on the VeryGenericIndicator**
Just added a conditional, to use the variable name if it exists

widget-manager: variableName as VeryGenericIndicator widget name

---

src/components/mini-widgets/ArmerButton.vue
src/views/ConfigurationAlertsView.vue

Close some tasks from #673
**Interface visibility/intuition improvements**

Change colors in switch components when toggled

---

src/components/widgets/Attitude.vue
src/components/widgets/Compass.vue
src/components/widgets/CompassHUD.vue
src/components/widgets/DepthHUD.vue
src/components/widgets/VirtualHorizon.vue
src/stores/widgetManager.ts

This patch leads to a huge improvement in Cockpit's performance, as it forces resource-intensive widgets that are not visible to not re-render.
I tried using the [checkVisibility](https://developer.mozilla.org/en-US/docs/Web/API/Element/checkVisibility) property, but it does not work on our case since the elements are in the DOM, just not on top.
On my computer, it reduced the CPU usage of the Cockpit tab in about 30%. It also prevented crashes that were happening when I left Cockpit open in the background.

Further performance improvements

---

src/libs/system-logging.ts
src/stores/development.ts
src/views/ConfigurationDevelopmentView.vue

It is still not saving objects correctly to the system logs. For some reason, stringifying them is causing a serious performance overhead, so I just kept them not being logged for now. As this already allows them to be printed by the console and extra console arguments to be printed as well, it's already a win.
Fix #685

system-logging: Make system logger print/log more than the first call argument

---

src/components/mini-widgets/MiniVideoRecorder.vue

In case a video recorder widget was never configured for some stream, it would throw an error instead of allowing selecting one.
Fix #690

mini-video-recorder: Fix starting records of unconfigured widgets

---

src/assets/defaults.ts
src/components/EditMenu.vue
src/components/mini-widgets/ViewSelector.vue
src/stores/widgetManager.ts
src/types/widgets.ts

@pkmiles you might want to check that out :)
Fix #696

Allow toggling visibility of Views

---

src/stores/alert.ts

Usually the speech language should be the same as the platform language, but it appears that some browsers have a weird default speech language. To be safer, we use by default the current platform language, and if that does not exist, the default speech language.

stores: alert: Use platform language by default over default speech

---

src/components/EditMenu.vue

Better match the suggestions in #448, by using the more commonly accepted dragging/reordering icon, and adding an up/down arrow to make it more obvious that reordering is possible.
Untested - spacing may need to be adjusted.

src: components: edit-menu: improve widget reordering icons

---

src/stores/controller.ts
src/views/ConfigurationJoystickView.vue

Stop sending MAVLink `MANUAL_CONTROL` commands when there's no pilot input

---

src/stores/widgetManager.ts

https://github.com/bluerobotics/cockpit/assets/6551040/bdb50c7c-302c-46e0-ad55-f7b1a9e60528
Fix #712

views: Consider visibility state of when selecting previous/next view

---

src/stores/widgetManager.ts

This prevents erratic behaviors, like the menu not opening because Cockpit was closed with it open.
Fix #723

widgets: Close widgets/mini-widgets configuration menus on boot

---

src/libs/vehicle/ardupilot/arducopter.ts
src/libs/vehicle/ardupilot/ardupilot.ts
src/libs/vehicle/ardupilot/arduplane.ts
src/libs/vehicle/ardupilot/ardurover.ts
src/libs/vehicle/ardupilot/ardusub.ts
src/libs/vehicle/ardupilot/types.ts
src/libs/vehicle/vehicle-factory.ts
src/stores/mainVehicle.ts

**Motivation:**
Adds the possibility to use cockpit in multivehicle environments, where people may be using multiple tools to monitor/track different robots and be connected to several mavlink sessions.
I personally use 20+ robots, where I need to gather and track information from multiple at the same time, and our setup and system is built around identifying robots by their ID. It will also allow us to use cockpit to start testing more smoothly without having to tear down entire existing system.
**Changes:**
* Add detection, storage, and handling of system_id
* Ardupilot has protected/export where we store the ID for later use
* Updated all functions I could find where I believe it to be required
* Remove/adapt code that excludes all vehicles except for 1
* Update the VehicleFactory …

Add support for non-default (1) vehicle ID (SYSID_THISMAV)

---

src/libs/utils.ts
src/stores/video.ts
src/views/ConfigurationVideoView.vue

Fix #736
Fix #751 
To be merged after #750

Improve video download page more

---

src/libs/vehicle/ardupilot/ardupilot.ts

With #740  merged, we can now use the ID for controllers, so they as well will function with a non 1 id.
Tested in SITL with rover.
* Arm/Disarm
* Turn
* Accelerate
* Confirm existence of manual control mavlink packets in websockets
Driven with controller in cockpit with this PR:

controller: Respect vehicle ID

---

src/components/WidgetHugger.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/components/widgets/Map.vue
src/libs/vehicle/ardupilot/ardupilot.ts
src/stores/widgetManager.ts
src/views/ConfigurationGeneralView.vue
src/views/MissionPlanningView.vue

- add missing await calls
- move variables to const and let where possible

Fix some stuff around the code

---

src/components/MiniWidgetInstantiator.vue
src/components/mini-widgets/ChangeAltitudeCommander.vue
src/components/mini-widgets/TakeoffLandCommander.vue
src/libs/vehicle/ardupilot/ardupilot.ts
src/stores/mainVehicle.ts
src/types/miniWidgets.ts

Adding the functionality to command altitude changes
closes #581 
https://github.com/bluerobotics/cockpit/assets/14896348/8dbfc8e7-7327-4922-b162-41447a4551eb

Change Altitude Mini-Widget

---

Dockerfile

I noticed when trying to install cockpit as an extension using blueOS on x86 the container was failing to run do to `exec /usr/bin/simple-http-server: exec format error`
I noticed there was no logic to wget the correct server architecture in the Dockerfile

Fixing Bug with Wrong simple-http-server Architecture Being Installed

---

src/components/EditMenu.vue
src/libs/utils.ts

Add check for TrackPad and horizontal scroll to avoid multiple wheel and scroll events to interact simultaneously.
Fixes #753

Fix widgets selection bar (on the edit-menu) removing multiple simultaneously scroll events

---

src/components/mini-widgets/MiniVideoRecorder.vue
src/components/widgets/VideoPlayer.vue

- Assert video is available before start recording
- Auto-assign stream (only if there's only one stream available)
- Let the user know if the selected stream is loading or not available
Fix #773 
Fix #270 
Fix #763 
Fix #764

Treat edge-cases on the VideoPlayer and MiniVideoRecorder

---

src/libs/sensors-logging.ts

Examples of the logs before and after:
```
Dialogue: 0,0:0:111.00,0:0:112.00,
Dialogue: 0,0:0:112.00,0:0:113.00,
Dialogue: 0,0:0:114.00,0:0:115.00,
Dialogue: 0,0:0:117.00,0:0:118.00,
```
```
Dialogue: 0,00:02:00.79,00:02:01.79
Dialogue: 0,00:02:01.79,00:02:02.80
Dialogue: 0,00:02:02.80,00:02:03.81
Dialogue: 0,00:02:03.81,00:02:04.79
```
Fix #625

sensors-logging: Fix calculation of duration intervals to consider milliseconds

---

src/libs/sensors-logging.ts
src/views/ConfigurationLogsView.vue

https://github.com/bluerobotics/cockpit/assets/6551040/32fff1ab-7efb-4cdc-afc3-ede605588d86
Depends on #739 
Fix #601

Allow adjusting telemetry interval

---

src/libs/joystick/protocols/mavlink-manual-control.ts
src/libs/vehicle/ardupilot/ardusub.ts

Fixes #786.
⚠️ **UNTESTED** - I just figured I'd get the code started, and hopefully someone can comment if there's something obvious I'm missing.
If possible it would be nice to have the mode and joystick button disabled for firmwares that don't support them (e.g. for non-ArduSub vehicles, and ArduSub <4.5), or at least provide an obvious warning when trying to switch to it (this may already happen if the vehicle rejects the mode change - not sure), but I'm not sure how to do either of those things.
@clydemcqueen may have some input as well.
---
@rafaellehmkuhl as a small comment, it seems weird to me to have to put the same information in twice in the `mavlink-manual-control.ts` file - could the button function actions not be added dynamically using the `MAVLinkButtonFunction` enum?

Add `SURFTRAK` mode support for ArduSub

---

src/App.vue

Add a check before opening hamburger configuration menu while vehicle is armed to avoid users changing configurations while vehicle still armed preventing potential dangerous actions
Closes #730

Add check before opening hamburger config menu while vehicle is armed

---

public/site.webmanifest

Without it, the user has to open the browser menu and use the hidden "install this site as app" option.

Make PWA app installation icon appear on browsers

---

src/stores/video.ts

This PR addss some small pre-commits so it gets easier to review the next one, which will change the video recovery logic.

We love video here

---

src/libs/vehicle/ardupilot/ardupilot.ts
src/libs/vehicle/types.ts
src/libs/vehicle/vehicle.ts

Notifies user when COMMAND_LONG fails. 
https://github.com/bluerobotics/cockpit/assets/14896348/59a7c09d-576e-41e6-a7fc-3190e3839936
closes #628

Add Logic to Check Result of COMMAND_LONG

---

src/components/mini-widgets/ModeSelector.vue

closes #742 
This change fixes an issue where a user selects a new mode to change the vehicle to, but the mode does not change.  This happens because the mode selector is commanding a mode change based on when the variable `currentMode` is changed. This variable is driven off of 2 sources. 
- 1.) the selection from the drop down menu. 
- 2.) the telemetry. 
When a user changes the dropdown menu selection, it triggers the mode change command, but the mode change command doesn't happen fast enough so that the next telemetry update changes the drop down mode back to the original mode which triggers another command to the vehicle to change the mode back to the original state. 
A simple solution to this is to check in the watcher function if the desired mode is already the mode of the vehicle …

Bug Fix: Fixing Mode Change Selector Commanding Mode Change Back to Original Mode

---

src/libs/sensors-logging.ts
src/stores/video.ts
src/types/video.ts
src/views/ConfigurationVideoView.vue

This patch gets back the functionality of recovering videos when Cockpit was interrupted during a recording (tab closing, shut down, lid closed, etc).
On top of that, it also allows for a recovery on situations where for some reason a processing (triggered by the stop button) failed.
To be merged after #788.
Fix #777.

Allow recovering unprocessed videos

---

src/components/mini-widgets/MiniVideoRecorder.vue

The problem of one being able to start multiple recordings with the same widget was being originated by the fact that whenever the user clicked to start a recording, even if the widget was already connected, it tried to connect again.
Without this step, that was being awaited for, the user simply can't start two recordings simultaneously, fixing also the other problems that raised from this.
As a bonus, now clicking to start a recording starts it instantaneously.
Fix #804

mini-video-recorder: Stop reconnecting stream that is already connected

---

src/stores/video.ts
src/views/ConfigurationVideoView.vue

This is one of the cases where the user reloads the page or is too fast reloading after stopping, and the video didn't start to process. It was mistakenly removed from the failed check.
@JoaoMario109 this is the one I mentioned before. With this patch I couln't find failed cases anymore (besides the ones you raised on #804, which were there before the recovery PR).

video: Do not skip videos that  do not started processing when searching for failed ones

---

src/stores/video.ts
src/views/ConfigurationVideoView.vue

Tested with a 30 min video. I tried to open the video download page really quickly, and it was there for 1 or 2 seconds. Of course, I also tried by just reversing the if 😅.
https://github.com/bluerobotics/cockpit/assets/6551040/fcc3d834-30ca-45c1-ac41-91d4fb0e3b1c
To be merged after #808

Add progress banner to warn about videos being processed on background

---

src/views/ConfigurationVideoView.vue

This way, users don't receive a "no videos available" warn when it's in fact loading the database.
https://github.com/bluerobotics/cockpit/assets/6551040/e9b2473a-5877-4227-8c58-aa9e175c8546
To be added after #809.

Add loading state to video table

---

src/components/mini-widgets/MiniVideoRecorder.vue

video: add state variable & visual feedback to monitor video processing

---

src/components/mini-widgets/MiniVideoRecorder.vue
src/views/ConfigurationVideoView.vue

Also made a minor arrangement to the buttons on the video storage interface (modal and config screens)

video: Add button with files count badge to access stored videos modal

---

src/assets/joystick-profiles.ts
src/libs/joystick/manager.ts

The code had previously had the  "Xbox One Wireless Controller" as the "Xbox One S Controller [Bluetooth]"
"Xbox One Wireless Controller" :  https://devicehunt.com/view/type/usb/vendor/045E/device/02E0
"Xbox One S Controller [Bluetooth]" : https://devicehunt.com/view/type/usb/vendor/045E/device/02FD
Discovered from draft PR https://github.com/bluerobotics/cockpit/pull/799

Fixing Incorrect Xbox One S PID

---

src/views/ConfigurationJoystickView.vue

Add support for remapping in controller axis

---

src/views/WidgetsView.vue

Move away from if test to AsyncComponentLoader

views: WidgetsView: Use AsyncComponentLoader over if test

---

src/App.vue

Main menu and disarm slider will not coexist on the screen while opening the menu through the vehicle's 'disarm before opening menu' alert popover.

Disarming the vehicle using the warning modal when opening menu with armed vehicle is generating dead state #833

---

src/tests/libs/widgets-loader.test.ts
src/types/widgets.ts
vite.config.ts

Address: https://github.com/bluerobotics/cockpit/pull/836#pullrequestreview-1954832393

Add test to check if widget enum matches widgets names

---

src/components/MiniWidgetInstantiator.vue
src/tests/libs/widgets-loader.test.ts

Use AsyncComponentLoader with mini-widgets

---

src/components/mini-widgets/VeryGenericIndicator.vue

Configuration modal will pop up whenever an unconfigured VeryGenericIndicator is instantiated. The modal closing is only permitted when the user has already selected a variable to be monitored by the mini-widget.
Fix #598

mini-widgets: VeryGenericIndicator pops up config modal when added

---

src/components/VideoPlayer.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/views/ConfigurationVideoView.vue

- Add video-js library and video player on a popover from the stored videos table;
- Add some minor ui changes, expanding the clickable area that opens stored videos modal at the miniVideoPlayer widget;
Fix #772

772 we should allow users to watch recorded videos (or parts of it) in the video view

---

.github/workflows/ci.yml

The fix on #853 strangely worked only on the PR itself. This fix is working on other PRs (tested on #855).

ci: Run `apt update` before flatpak installation

---

.github/workflows/ci.yml
package.json

This is the name that goes to the application on the OS executable/shortcut.
As of now it's using the "name" tag by default, which enforces camelCase.

package: Add `productName` tag

---

src/assets/joystick-profiles.ts
src/stores/controller.ts
src/stores/mainVehicle.ts
src/types/joystick.ts
src/views/ConfigurationJoystickView.vue

- Allows assigning different vehicle types to a joystick mapping
- Auto-set joystick mapping on boot based on vehicle type
Fix #858 
Fix #859

Tie vehicles to joystick profiles

---

src/components/MiniWidgetContainer.vue

mini-widgets: Only highlight when in edit-mode

---

src/views/ConfigurationGeneralView.vue

This patch prevents the user from using bad global addresses, that will for sure not work or can break Cockpit.
Fix #893

Supress invalid global address

---

src/components/Dialog.vue

Change from using 'cancel' event from dialog element to use keydown and listener for ESC key, since edge does not implements 'cancel' event handler but the behavior still triggering preventing the menu to reopen after closed using ESC in edge.
Fixes #889

Change from using 'cancel' to use 'keydown' in Dialog.

---

src/components/widgets/VideoPlayer.vue
src/composables/webRTC.ts
src/libs/webrtc/session.ts
src/libs/webrtc/signaller.ts
src/stores/video.ts
src/types/video.ts

This patch adds status for the signalling server and the stream connection on the video widget.
It also fixes some minors.
There's more to come, but I didn't want to hold bigger changes to get the fix in.
Fix #664 
Fix #684 
Fix #813

Add feedback on video connection

---

src/App.vue
src/components/widgets/Map.vue
src/stores/widgetManager.ts

Now the bottom bar has a dynamic size, that is exposed to everyone. This allows for components like the `SlideToConfirm`, or widgets like the `Map` to use only the visible widgets area (and prevent positioning of buttons under the bar).
The immediate change is that the `Map` widget now does not have its buttons "floating" in the middle of the widget, with a fixed height from the bottom edge. They can now react to the positioning of the widget itself with respect to the bottom bar, never being under it.
Before:
After:
https://github.com/bluerobotics/cockpit/assets/6551040/424d6f4c-9267-4b7d-a76f-94347c73f97c

Use dynamic positioning with respect to bottom bar

---

index.html

Also, only show "clear settings" fallback after the user agreed to proceed with the browser check, as they are different situations that shouldn't be shown together, to not confuse the user.
https://github.com/bluerobotics/cockpit/assets/6551040/d4c1307b-ac3f-4860-9abc-ee6e2fa7ebc9
Fix #906

fallbacks: Compatibilize style of browser and settings fallback banners

---

src/stores/video.ts

* Added a try-catch routine
* Removed redundant blob processing

Fix thumbnail generation method on video recording

---

src/libs/sensors-logging.ts

Telemetry logs are taking a lot of time to be processed, and looking more into it, I realized it is because we are accessing each log file individually and checking if it matches our criteria.
This patch fixes it with a quick and dirty solution: iterating first over the logs from the day of the video and the day before, and only them on the rest of the logs (which would be the case only for videos being recorded for more than 24 horus...).
The best solution would be to index the DB by timestamp, sort it and check the logs starting from the most recent one, with a proper cursor, but it is a more complex solution that I need to study more about, while the one here solves the problem already.
Fix #908

sensors-logging: Find log by day prioritizing those from the last day

---

src/stores/mainVehicle.ts

it results in some rather ugly urls, but it works 🤷

main-vehicle: allow setting vehicle and stream urls via query

---

src/components/VideoLibraryModal.vue

This forces it to handle well videos with different aspect-ratios, like 4:3.
Fix #930.

video: Use fixed aspect-ratio on the library

---

src/stores/video.ts

It does not make sense to have it anymore, as it's now clear that the videos are there (from the `MiniVideoRecorded` badge).

video: Remove warning about available videos

---

src/libs/blueos.ts
src/stores/video.ts

This situation leads to the ICE negotiation failing (since we are not allowing any of the available IPs), and thus no video stream being loaded.
For the future, we should change all those SweetAlerts by our own library, probably using the `InteractionDialog` component. This is probably part of #875.
Fix #661.

video: Warn user if they selected an IP that is not available in the ICE candidates

---

src/App.vue
src/components/MiniWidgetContainer.vue
src/components/mini-widgets/VeryGenericIndicator.vue
src/libs/sensors-logging.ts
src/stores/widgetManager.ts
src/types/miniWidgets.ts
src/views/ConfigurationLogsView.vue

- Allow logging of any variable the vehicle offers;
- Custom VeryGenericIndicators now must have a Name and a variable to be accepted;
- Unique Display Name for VeryGenericIndicators from now on. They can monitor the same variable, but with different display names. This is the reference for logging.
Closes #600

Allow logging data from very generic indicator

---

src/composables/webRTC.ts
src/libs/webrtc/session.ts
src/stores/video.ts
src/views/ConfigurationVideoView.vue

This patch allows us to control the [RTP receiver target jitter buffer](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpReceiver/jitterBufferTarget).
The default value is set to zero, which gives us the minimum possible latency for the stream. 
From my tests, setting it to zero improved latency compared to the browser's default (unbeknownst to me).

Add RTP receiver jitter buffer target configuration

---

src/components/mini-widgets/MiniVideoRecorder.vue

mini-video-recorder: Disallow recording a stream that is not connected

---

src/components/mini-widgets/VeryGenericIndicator.vue
src/libs/vehicle/ardupilot/ardupilot.ts
src/stores/mainVehicle.ts

This patch makes:
- searching for available generic variables happens only every 5 seconds (instead of with each received message)
- retrieve data only for the messages/variables being used (and happens with direct access instead of search)
#937

Optimize parsing of generic messages data

---

src/libs/sensors-logging.ts
src/views/ConfigurationLogsView.vue

* Based on @ES-Alexander's idea and wireframes;
* #621
* User can configure details of the on-screen subtitle data telemetry display;
* Telemetry frequency configuration on separate tab;

Improve subtitle telemetry display and configurations

---

src/libs/blueos.ts
src/stores/mainVehicle.ts

Apart from solving the problem, this implementation exposes how coupled things are right now regarding the vehicle store and the data used by the widgets (like the `VeryGenericIndicator`). We should improve the discussion around how to better accomplish that so that it's more natural to add this kind of feature.
Fix #956

blueos: Allow monitoring BlueOS CPU temperature with the VeryGenericIndicator

---

src/components/VideoLibraryModal.vue

* Added extra conformation button on Video Delete;
* Modified confirmation buttons positions and animation;
Fix #951

Improve video deletion UI

---

src/components/widgets/Compass.vue
src/components/widgets/VirtualHorizon.vue

The canvas itself is being resized with the resizing of the widget (which happens when the user resized the window or the widget on edit-mode), which causes the canvas to be cleared. We solve this by forcing the render when the size changes.
Fix #909

Force rendering of `Compass` and `VirtualHorizon` on widget resizing

---

package.json
src/App.vue
src/components/GlassButton.vue
src/components/InteractionDialog.vue
src/composables/interactionDialog.ts
src/stores/appInterface.ts
tailwind.config.js

* Main menu, glass version - already with the modifications from cockpit meeting in 06/03/24;
* Responsivity logic using Tailwind breakpoints and Pinia store;
* Configuration menu items added;
Running on different device screen resolutions:
Closes #968

Implement new main menu and responsivity logic

---

src/components/WidgetHugger.vue
src/components/widgets/Map.vue
src/stores/widgetManager.ts

With this patch, widgets will not go under the top/bottom bar when the window is resized, nor the user will be able to move a widget to under the bars, with the exception being full-screened widgets.
I will keep this as draft for now to make sure I'm happy with the solution, and I've tested for all edge-cases.
Fix #634 
Before:
https://github.com/bluerobotics/cockpit/assets/6551040/9fca0261-f944-418a-82a2-60eef3b4d7d0
After:
https://github.com/bluerobotics/cockpit/assets/6551040/f7228c3c-023e-4fd9-a6df-e2b86a0dfe75
https://github.com/bluerobotics/cockpit/assets/6551040/43be5008-494c-4a1f-949c-c86230a19796

Move widgets away from bars

---

src/libs/vehicle/ardupilot/ardupilot.ts

ardupilot: Fix population of available generic variables array with the `NAMED_VALUE_FLOATs`

---

src/components/InteractionDialog.vue
src/components/VideoLibraryModal.vue
src/stores/video.ts

With this patch we start to warn the user if a chunk fails to be written to disk, as well as if the chunk recording takes more than 5 seconds. The warning says that the system is having trouble saving the record, that parts of the video can be lost, and therefore it's suggested to start a new recording.
The warning is emitted at most once per recording.
This patch also allows the video processing to proceed when the duration-fix fails, delivering a video without the duration fixed.
Fix #977
Fix #993

Warn user when video recording starts to fail

---

src/components/VideoLibraryModal.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/stores/video.ts
src/types/video.ts

This patch reduces in about 70% the time to download a video.
Videos with 22 minutes (1.1GB) that were taking around 36 seconds to be downloaded, now take around 10 seconds. To reduce this time, I configured the file compressor to level zero, which makes it not compress the video at all, and only write it to the zip file. This does not affect the file size since the `.webm` video is already compressed.
Despite that, considering that even 10 seconds is a lot of time for the user, considering that they don't know if the download is going to proceed or not, I've added a progress feedback, which tells the user how far he is from having his video downloaded.
https://github.com/bluerobotics/cockpit/assets/6551040/fa382769-94bc-4c33-bf0e-2a860471a3d1
Now, even if the download takes a little …

Make video download faster (and give proper feedback)

---

src/components/VideoLibraryModal.vue
src/components/VideoPlayer.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/stores/video.ts
src/types/video.ts

The video files now have the correct extension and all hardcoded mentions to WEBM in the repository are removed.
The `fixWebmDuration` lib is the only exception, as despite the name it fixes the duration for any chunk type.
Fix #999.

Fix video extension

---

vite.config.ts

This prevents cases where the server is only accessible from the host IP.

vite: Force server on `0.0.0.0`

---

src/stores/mainVehicle.ts
src/stores/video.ts
src/views/ConfigurationGeneralView.vue

Fix address reactivity in general configuration view

---

src/stores/mainVehicle.ts
src/views/ConfigurationGeneralView.vue

This patch allows a persistent configuration of the WebRTC configurations. This allow the usage of Cockpit with BlueSim.
To test it, open a BlueSim instance and access the following address:
`http://localhost:5173/?webRTCConfiguration={"iceServers":[{"urls":"stun:stun.l.google.com:19302"}]}&webRTCSignallingURI=ws://BLUE-SIM-IP:6041`
You can also remove the "webRTCConfiguration" from the query parameters and set it directly in the general configuration menu. The "webRTCSignallingURI" parameter is needed since setting it in the menu is broken until #938 is merged.
Fix #925

Allow changing the RTC configuration

---

src/components/widgets/VideoPlayer.vue

video-player: Improve message for when the selected stream is not available, but there are others

---

src/App.vue
src/components/ExpansiblePanel.vue
src/components/GlassButton.vue
src/components/GlassModal.vue
src/components/InteractionDialog.vue
src/composables/interactionDialog.ts
src/styles/global.css
src/views/BaseConfigurationView.vue
src/views/ConfigurationGeneralView.vue

Main features:
Main menu and configs submenu responsiveness with simplified versions for small screen devices;
New Modal and Expansible-panels Vue components;
Refactoring of General Configurations component to suits the new UI and fit on different screen sizes;
Main responsiveness logic (store and Tailwind) updated;
Information/help drawers added:
https://github.com/bluerobotics/cockpit/assets/14910201/42f0ea58-63fc-4c35-a8dc-b356134924bb
Regular size screens:
https://github.com/bluerobotics/cockpit/assets/14910201/c8c67845-fcf5-43a7-8d1f-d2e2477f4e4a
Very small screens:
https://github.com/bluerobotics/cockpit/assets/14910201/63df7c5b-4140-4fb6-99f5-6a55bec1110e
Closes https://github.com/bluerobotics/cockpit/issues/969

Implement new UI to Configurations - general

---

src/views/ConfigurationAlertsView.vue

To be merged after #1020
Using the same UI philosophy implemented on #969 
Closes #973

Implement new UI to Configurations - Alerts

---

src/views/ConfigurationMissionView.vue

To be merged after #1020 
Using the same UI philosophy implemented on #969 
Closes #975

Implement new UI to Configurations - Mission

---

src/components/GlassModal.vue
src/views/ConfigurationDevelopmentView.vue

Implement new UI to Configurations - Telemetry

---

src/components/widgets/IFrame.vue

Right now I'm positioning the actual iFrame element. 
~I will try to do that with the iFrame widget, so it doesn't add extra position/size logic and supports native widget features (like the toolbar repositioning).~ I think we can leave with that for now, so I've opened #1043 to track future improvements on that.
https://github.com/bluerobotics/cockpit/assets/6551040/56d144df-721c-4320-915a-08cb6ea140ea
Fix #731

iframe: Persist position on DOM so it doesn't reload on view change

---

src/components/mini-widgets/DepthIndicator.vue

No other widget uses time-averages as of now. If we decide on something like that, it should be user configurable, so it does not generate doubts on the widget behavior.
Fix #1037

depth-indicator: Remove time-averaging

---

src/assets/defaults.ts
src/components/WidgetHugger.vue
src/composables/settingsSyncer.ts
src/libs/blueos.ts
src/libs/sensors-logging.ts
src/stores/alert.ts
src/stores/controller.ts
src/stores/development.ts
src/stores/mainVehicle.ts
src/stores/mission.ts
src/stores/video.ts
src/stores/widgetManager.ts
src/types/miniWidgets.ts
src/types/widgets.ts
src/views/ConfigurationJoystickView.vue
src/views/ConfigurationLogsView.vue

This is a major patch, that changes how Cockpit works with its settings fundamentally.
With it, instead of having the browser `localStorage` as the source of truth for its settings, Cockpit now uses the backend (provided here by the bag-of-holdings service on BlueOS) to sync Cockpit's storage with BlueOS.
There's a pipeline, where Cockpit first tries to fetch its settings from BlueOS. We call it the initial sync. If the values differ, the user will be asked which one they want to keep.
After a successful sync, it then starts to use its own variables, now synced, as the new source of truth. We do that so the settings are always stored in the vehicle, but in the case the user changes something in Cockpit, this change is pushed to the BlueOS storage as the new (updated) value.
In case …

Auto-sync Cockpit settings with BlueOS

---

src/stores/mainVehicle.ts

generic-variables: Fix watcher for newly tracked generic variables

---

src/stores/development.ts

I mistakenly copy-pasted it in the previous PR.

blueos: Fix string used for the BlueOS settings sync activation

---

src/stores/video.ts

video: Accept `USB` connections as valid tethered and automatically assign them

---

.github/workflows/ci.yml

macos-14 has some problems when generating the artifact
Fix #1062

ci: Wrap tag releases with zip

---

src/components/joysticks/JoystickPS.vue

This way the standalone Electron app can also load it.
Fix #882

joystick-config: Use relative path for joystick SVG file

---

src/libs/vehicle/ardupilot/ardupilot.ts

Left Cockpit running for an hour an it didn't reach 200MB (without a camera connected).
Before:
https://github.com/bluerobotics/cockpit/assets/6551040/b8348dc5-8eb4-4128-b687-112480a17b4b
After:
https://github.com/bluerobotics/cockpit/assets/6551040/e5204aa3-9c5d-4d71-9190-f57f5c80c01e
Fix #1027 
Fix #1047

ardupilot: Do not duplicate path of available generic variables

---

src/composables/interactionDialog.ts

I love when those issues where we spend hours debugging and the solution was in one line of code. 
Happy to have solved this one. Was driving me crazy.
Fix #1054

interaction-dialog: Don't share the resolve/reject state between different instances

---

Dockerfile

Cockpit README is not showing in BlueOS

Dockerfile: Add missing readme label

---

src/components/VideoLibraryModal.vue
src/stores/video.ts
src/views/ConfigurationVideoView.vue

Download files separately by default. This makes the download process instantaneous, which is specially important on longer videos.
The user can choose in the video configuration menu if they want to zip by default.
Fix #1076.

video: Allow user to choose between zipping multiple video files or not

---

src/App.vue
src/components/GlassModal.vue
src/components/VideoLibraryModal.vue
src/stores/appInterface.ts
src/views/ConfigurationGeneralView.vue

* User can now control the glass interface color, blur and opacity via sliders an color pickers on the Configurations-General menu;
https://github.com/user-attachments/assets/e18e5cb3-e52f-4259-a2a2-a0c1bfd34f25
closes #1104

Add color and opacity controls to the glass interface elements

---

src/components/InteractionDialog.vue

Since there are already use cases where everything is optional, including `variant` and `message`, and we already have defaults for those, we make everything optional and remove the unnecessary warnings that we currently have.

interaction-dialog: Make all variables optional

---

src/assets/defaults.ts
src/components/EditMenu.vue
src/components/MiniWidgetContainer.vue
src/components/WidgetHugger.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/components/mini-widgets/VeryGenericIndicator.vue
src/components/widgets/Attitude.vue
src/components/widgets/Compass.vue
src/components/widgets/CompassHUD.vue
src/components/widgets/DepthHUD.vue
src/components/widgets/IFrame.vue
src/components/widgets/ImageView.vue
src/components/widgets/Map.vue
src/components/widgets/MiniWidgetsBar.vue
src/components/widgets/URLVideoPlayer.vue
src/components/widgets/VideoPlayer.vue
src/stores/widgetManager.ts
src/types/widgets.ts
src/views/WidgetsView.vue

This PR removes the `managerVars` object from the structure of the widgets and mini-widgets.
Those variables, that are part of the state of the application session, and not of the object itself, won't be carried around with them anymore.
The biggest advantage of doing that is that the widget settings objects won't be updated anymore when a widget variable state is updated, so features that react to that, like the BlueOS settings sync, won't be triggered anymore unnecessarily.
I've tried to bind the `managerVars` method to the objects, so we wouldn't need to access this method through the store itself, but I had several troubles with this implementation regarding the serialization of this object, so I decided to not carry with this since we are approach a release candidate and this patch …

widgets: Make manager vars non-persistent

---

src/stores/video.ts
src/views/ConfigurationVideoView.vue

This feature was asked by one of our users, which has a BlueOS based vehicle, but does not want the auto-retrieval feature, since he has an unusual network configuration where there are thetered connections but they do not want the video to come exclusively from that source.
Fix #1107.
@goasChris it would be nice if you could test it before we merge, to see if it fullfils the case.

video: Allow user to disable auto-retrieval of thetered IP addresses from BlueOS

---

src/stores/mainVehicle.ts
src/stores/widgetManager.ts

The global address does not make sense to sync, since when the user is already connected for the sync to work, and changing the address can only disconnect them.
The widgets profile and view index also does not make much sense since they are actually states, not settings. It may be something the user is messing around with before connection and will receive a conflict unnecessarily.

settings-sync: Remove profile and view indexes and global address from auto sync

---

src/components/mini-widgets/DepthIndicator.vue

Before and after:
https://github.com/user-attachments/assets/6b2d5af0-b358-4de8-8b71-6c05ade0ee7a
https://github.com/user-attachments/assets/a52e82bb-6287-4222-a521-0afceabb3e0b
Fix #1127

depth-indicator: Improve it so the numbers and icon don't move

---

src/components/mini-widgets/VeryGenericIndicator.vue

In situations where the value+unit was not using the full width of the widget, the display name was being cropped unnecessarily.
Before/after:

vgi: Always use full available size for the display name

---

src/components/EditMenu.vue

Fixes broken paths for wodgets images when cockpit is running as a BlueOS extension

Edit Mode: Fix widget images relative paths

---

src/components/widgets/Attitude.vue

This makes the widget behave as it did before the camera compensation when paired with older ardupilot versions with no gimbal_device_attitude_status messages

attitude-widget: handle non-existing gimbal message in older firmware

---

src/libs/vehicle/ardupilot/ardupilot.ts

With how it was till now, arrays would be broken and not proper paths.
Can be tested by checking that previously the `GIMBAL_DEVICE_ATTITUDE_STATUS` message in the MAVLink stream wouldn't have the `q` property properly parsed. Now it is.

generic-variables: Allow generic variables with array values

---

src/App.vue

* Bars now will scale down on small screens to fit its width;
* Bars now share the glass material selected by the user on the configs/Interface menu
https://github.com/user-attachments/assets/c9edd184-5752-49e9-af69-06f51c847ed9
Closes #1035

Add responsiveness to top and bottom bars

---

src/components/widgets/Attitude.vue
src/components/widgets/VirtualHorizon.vue

Turns out my camera was inverted, and the Attitude widget was rolling to the right direction. The one going to the wrong direction was the VirtualHorizon.
Shame on me for breaking things that were working. At least it served for us to find a problem in the VirtualHorizon. Thanks @Williangalvani for noticing.
For those reviewing this PR I ask that you check twice to make sure I didn't make the same mistake twice 😅

attitude: Fix horizon directions on attitude widgets

---

.github/workflows/ci.yml
src/App.vue
src/components/EditMenu.vue
src/components/InteractionDialog.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/components/mini-widgets/VeryGenericIndicator.vue
src/components/widgets/Map.vue
src/components/widgets/VideoPlayer.vue
src/composables/interactionDialog.ts
src/composables/settingsSyncer.ts
src/libs/joystick/protocols/mavlink-manual-control.ts
src/libs/sensors-logging.ts
src/libs/utils.ts
src/stores/appInterface.ts
src/stores/controller.ts
src/stores/video.ts
src/stores/widgetManager.ts
src/views/MissionPlanningView.vue

* Added 'auto close on timeout' function to InteractionDialog
* Small changes on dialogs UI
Closes #1117

Replace SWALs with Interactive Dialogs

---

src/main.ts
src/stores/omniscientLogger.ts
src/stores/video.ts

The average framerate is logged at debug level every second, while the framerate drop logs happen if a 10% threshold is archieved.
I've evaluated the application for any performance loss but couldn't notice any.
Fix #1162
Fix #1163

Add framerate logging for both application rendering and video streams

---

src/libs/joystick/protocols/mavlink-manual-control.ts

This commit updates the button filtering logic in the MavlinkManualControlManager class. The code now filters buttons based on their names and includes only those that contain 'BTN' and 'FUNCTION'. This change ensures that only the button function parameters are used.
The commit also adds a check to skip the buttons system if the vehicle has no button parameters.
Fix #1168

mavlink-manual-control: Skip button remapping logic if vehicle has no button parameters

---

src/stores/video.ts

The titles were too big and the messages were broken.
Fix #1182

video: Fix title and messages of the IP routing warnings

---

src/stores/omniscientLogger.ts

Warn only about the cumulative ones that should not increase. This was needed because some of the values should indeed increase, normally.
Fix #1187

performance: Log more webrtc stats

---

src/libs/communication/mavlink.ts

If the vehicle was still not connected and we tried sending any MAVLink message, this channel would die.

mavlink: Catch error when sending mavlink messages through the websocket connection

---

src/views/WidgetsView.vue

widgets: Warn user when they have no widgets in the view

---

src/components/widgets/Compass.vue
src/components/widgets/CompassHUD.vue
src/components/widgets/DepthHUD.vue
src/components/widgets/VirtualHorizon.vue

The thing was that they were in the background when mounted, so their canvas contexts were not in the DOM or had zero heigh/weight, causing the initial render to fail.
With this PR they are always rendered when they appear on the screen.
Fix #1154

widgets: Fix canvas rendering for widgets that are in the background

---

src/components/EditMenu.vue

edit-mode: Get snap-to-grid toggle back

---

src/stores/mainVehicle.ts

They are specific for each user connection, so it's hard to just sync them without thinking about it. It's giving unnecessary conflicts in this case.
Fix #1254

auto-sync: Remove all connection URIs from the auto-sync

---

src/components/mini-widgets/MiniVideoRecorder.vue
src/components/widgets/VideoPlayer.vue
src/composables/settingsSyncer.ts
src/stores/widgetManager.ts

This solves the problem of someone resetting the widgets profiles and receiving a conflict in the next reload.

Prevent conflicts after resetting profiles

---

src/App.vue
src/components/VideoLibraryModal.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/stores/appInterface.ts
src/views/ConfigurationVideoView.vue

From a @ES-Alexander and Kurt discussion, was decided that we should provide a permanent link to the Video Library, even if there is no file stored there.
Anyway, soon the video storage on BlueOS cloud will be implemented and we would have to provide this permanent link.
On the image, (1) and (2) are permanent links.

Cockpit should have a permanent link to the video library

---

src/stores/omniscientLogger.ts

webrtc: Warn about changes in stats that should not change

---

src/stores/widgetManager.ts

This actions is usually triggered by the joystick, so it's a bummer to have to wait the dialog disappears or to reach the mouse to click the close button.

widgets: Use snackbar instead of dialog if next-view action fails

---

src/components/mini-widgets/JoystickCommIndicator.vue

https://github.com/user-attachments/assets/8009eeb8-1478-4e4a-a55f-2b6f9fdfafdb
Fix #1311

joystick: Allow user to disable the joystick

---

src/App.vue
src/styles/global.css

* Changed the highlight color to 'bight yellow'
* Changed the highlight duration from 20 to 50 seconds
Fix #1335

Components: Tutorial: Make highlights more visible - color and duration

---

src/libs/joystick/protocols/mavlink-manual-control.ts

Reduced ambiguity about what is wrong, and what to do about it.
Original message was a source of confusion [in this forum post](https://discuss.bluerobotics.com/t/message-while-assigning-servo-function-to-controller-button/17990).
It would be nice if we could also recommend updating firmware where that's a viable solution, but that would require a dynamic check, and I believe there's already a message about it at the top of the joysticks page for users with a firmware that doesn't support the extended MAVLink Manual Control protocol (and the extra button slots it provides)

libs: joystick: improve "button slots full" error

---

src/components/EditMenu.vue

edit-mode: Resize mini-widget placeholders if they overflow container

---

src/stores/mainVehicle.ts
src/stores/mission.ts
src/views/MissionPlanningView.vue

* Updated the mission planning UI to Cockpit glass style;
* Added multi survey/mission functionality, so users can make complex surveys patterns;
https://github.com/user-attachments/assets/1145a58a-6b4a-4615-9209-3a5af856a3d3

Add cockpit theme to mission planning

---

src/components/GlassModal.vue
src/components/Tutorial.vue

**From @ES-Alexander feedback:**
* Tutorial window now is draggable;
* Tutorial starts on step 1 after closed;
* Element highlighting leak fixed (was highlighting components after tutorial closing);
* First button renamed to 'Start';

Tutorial: Make small adjustments based on internal user's feedback

---

src/components/mini-widgets/BatteryIndicator.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/libs/sensors-logging.ts
src/stores/mainVehicle.ts
src/stores/widgetManager.ts

Adds instantaneous power and total power consumption to the BatteryIndicator widget.
https://github.com/user-attachments/assets/fa160e7c-e3cf-4678-9d9c-069902542f88
Fix #1368

Add instantaneous power and total power consumption

---

src/components/mini-widgets/MiniVideoRecorder.vue
src/components/widgets/VideoPlayer.vue
src/stores/video.ts
src/views/ConfigurationVideoView.vue

Now user can double click the stream name or press the 'pencil' icon to change its internal name:
https://github.com/user-attachments/assets/524e7c78-e32e-4c39-8766-c9d892d98153
Closes #1336

Add input to rename internal video streams

---

src/components/EditMenu.vue
src/components/widgets/Map.vue

From @ES-Alexander feedback:
* Prevent map from being interactive during edit-mode;
* Added paddings on the widget and mini widgets add bar;
* Fixed some text inconsistencies pointed by ES-Alexander;
* Fixed positioning on various components;
* When adding mini-widgets, cards are no longer being dragged together;
* Fixed mouse hovering icon/info is inconsistency over different parts of the widget cards;
* Prevent main menu tab from being visible during edit-mode;

Edit-menu: Modify interface from users feedback

---

src/components/ExpansiblePanel.vue
src/components/mini-widgets/JoystickCommIndicator.vue
src/stores/controller.ts
src/types/joystick.ts
src/views/ConfigurationJoystickView.vue

* Increased support for up to 32 axis and buttons;
* Solved a bug that broke the DOM when activating joystick inside the Joystick Config Page;
* Fixed the alert icon visual feedback causing a horizontal scroll to show on joy-config-page.
* Improved Visual feedback for joystick table;
https://github.com/user-attachments/assets/8b939ff6-521d-4c33-949a-6dc0c3dd1ade
Closes #1208

Improve joystick support for up to 32 axes and buttons

---

src/components/EditMenu.vue

Edit-menu: Fix mini-widget card width

---

src/stores/controller.ts

Based on issue #728 where the user suggested a confirmation for successfully importing functions mapping onto the joystick profile.
Closes #728

Joystick: Add visual feedback for functions importing

---

src/libs/system-logging.ts
src/views/ConfigurationDevelopmentView.vue

Console logs can have a huge impact on performance, especially on low-end devices.
Also allows user to delete one or multiple logs.
I've also added a message to the console, before disabling it, so users that want to see the console know what to do.

system-logs: Do not log to console when system-logging is enabled

---

src/App.vue
src/libs/actions/data-lake.ts
src/libs/actions/http-request.ts
src/libs/joystick/protocols.ts
src/libs/joystick/protocols/cockpit-actions.ts
src/stores/controller.ts
src/stores/mainVehicle.ts
src/views/ConfigurationActionsView.vue

https://github.com/user-attachments/assets/7e64a286-4a72-4755-93a6-6e43636e273d
Import can be tested with the following action files:
[http-request-action (Arm with HTTP).json](https://github.com/user-attachments/files/17298873/http-request-action.Arm.with.HTTP.json)
[http-request-action (Disarm with HTTP).json](https://github.com/user-attachments/files/17298874/http-request-action.Disarm.with.HTTP.json)
Fix #568

Allow for dynamic Cockpit Actions and add support for customizable HTTP request actions

---

.github/workflows/ci.yml
package.json

Apparently the arm64 flatpaks that were being generated (previously to all those CI changes) were actually just renamed x86 flatpaks. 
This got caught during the CI changes (making the actions fail) as we aren't forcing the artifact names anymore. 
This is now fixed.

Fix generation of arm64 flatpaks

---

src/assets/defaults.ts
src/stores/mainVehicle.ts

This solves the case of the electron app (which has "localhost" as hostname) not automatically connecting.
It also automatically removes the protocol part of the address if for some reason it got there.

defaults: Fix once and for all (?) the global address

---

src/components/VideoPlayerStatsForNerds.vue

Adds a new red plot line for (instant) packet loss.
useful for correlating video freezes to packet loss

StatsForNerds: cleanup and plot packets lost

---

src/components/widgets/Map.vue
src/views/MissionPlanningView.vue

Change vehicle real path color

---

src/assets/defaults.ts
src/components/mini-widgets/VeryGenericIndicator.vue

* Added a new default profile for USVs;
* Added 'Decimal places' and 'Display width' parameters on the Very Generic Indicator custom component creator; so, it would be possible to display the boat speed correctly on the profile;
Closes #592

Add new default boat profile

---

src/components/widgets/Map.vue
src/composables/settingsSyncer.ts
src/libs/vehicle/ardupilot/ardupilot.ts
src/views/MissionPlanningView.vue

* Increased the timeout for mission upload and download on the ardupiot library. Long missions and surveys were not being transferred due to short time limit on  comm requests;
* Relocated and improved the linear progress bar that provided visual feedback for the mission transferring processes.

Fix mission planning UI issues

---

.eslintrc.cjs
src/components/configuration/MavlinkMessageActionConfig.vue
src/libs/actions/mavlink-message-actions-message-definitions.ts
src/libs/actions/mavlink-message-actions.ts
src/views/ConfigurationActionsView.vue

Any message is accepted as long as it's a valid MAVLink message.
For `COMMAND_LONG` and `COMMAND_INT` messages, the message fields are pre-defined in the UI. For all other messages, the user should specify the JSON message config manually.
I pretend to do a proper automatic parser for all messages soon.
Fix #825 
Fix #826

Add MAVLink message actions

---

src/libs/actions/data-lake.ts

Listeners are not notified about this initial value. This allows those creating variables to have an initial value that is based on its internal logic (e.g.: persistency between sessions).

data-lake: Allow passing initial value on variable creation

---

src/components/mini-widgets/Alerter.vue

I performed about a week of testing with Cockpit to learn more about its performance issues.
A detailed report can be found [here](https://drive.google.com/file/d/16AU_I-ApkT_wr5BrxqQqev9EvYgOylnw/view?usp=sharing), but I will make a resume below.
I could find that we indeed have a big memory leak that causes the application to become slow after about 20 minutes and to crash after around an hour (depending on the computer specs). After a lot of tests I could determine that this leak is caused by a `v-tooltip` component that is used in the expanded list of the `Alerter.vue` widget. This component is instantiated for every alert in the list, and is never garbage-collected, so for every new alert added to the list, a series of zombie components are created and left there forever. This PR …

Seek and destroy main memory leak

---

src/components/About.vue
src/libs/cosmos.ts
src/libs/non-browser-utils.ts
src/utils/version.ts
tsconfig.app.json
vite.config.ts

Calculates version based on last git tag or current commit hash (fallback). Works on browser, dev mode and Electron.
Also fixes the problem of not being able to reopen the about page after closing it by clicking outside the dialog.
<br/>
<p align="center">
<p/>
<br/>
Fix #1315

general: Inject dynamic version to about page

---

src/components/ExpansiblePanel.vue
src/views/ConfigurationJoystickView.vue

It was mistakenly warning about the `MANUAL_CONTROL` message not being supported when it failed to fetch the information from BlueOS.
Fix #1067

joystick-config: Fix warning about manual-control message not being supported

---

src/components/MiniWidgetInstantiator.vue
src/stores/mainVehicle.ts

Handle errors that where being raised without need and polluting Sentry's dashboards.
Opened #1466 and #1467 for the other two changes.

Improve error handling

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.vscode/settings.json
.vscode/tasks.json

Adds a development environment matching production,
requires minimal setup without any additional installations.
**DevContainer:**
DevContainer can be used on VSCode through [VS Code DevContainer extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)
Or from Github's Codespace:
Codespace created demo:
Codespace running task live DevServer:
Codespace loading DevServer from forwarded port:
**Tasks:**
Now users can run live DevServer through container or directly when it's inside DevContainer:
Tasks pannel:
Tasks on botton pannel:

Add: DevContainer Support & Tasks

---

src/libs/actions/data-lake.ts
src/stores/omniscientLogger.ts

Allows the user to consume this data from data-lake-ready widgets.

omniscient-logger: Populate data-lake with Cockpit's memory usage

---

electron/main.ts
electron/preload.ts
electron/services/network.ts
src/App.vue
src/components/InteractionDialog.vue
src/components/VehicleDiscoveryDialog.vue
src/libs/cosmos.ts
src/libs/electron/vehicle-discovery.ts
src/views/ConfigurationGeneralView.vue
vite.config.ts

Add vehicle discovery

---

electron/preload.ts
electron/services/network.ts
src/components/VehicleDiscoveryDialog.vue
src/libs/cosmos.ts
src/libs/electron/vehicle-discovery.ts
src/types/network.ts

The vehicle usually has some IPs generated by it's own servers (e.g.: 192.168.3.1 for USB C connections), which offers a dynamic IP for the topside computer. With this change, those IPs are also findable.
Before and after:
This commit is the correct implementation that I changed during the review process, and should be [in the original PR](https://github.com/bluerobotics/cockpit/pull/1471), but I lost it during the rebase. My bad.

vehicle-discovery: Allow finding IPs generated by a DHCP server in the vehicle

---

src/libs/external-telemetry/event-tracking.ts

Realized we need that when the PostHog server started registering several events from Florianopolis without a release being done.

event-tracking: Disable if not in production or user opted-out

---

src/components/ElementConfigPanel.vue
src/components/MiniWidgetInstantiator.vue
src/components/configuration/HttpRequestActionConfig.vue
src/components/custom-widget-elements/Checkbox.vue
src/components/custom-widget-elements/Dial.vue
src/components/custom-widget-elements/Dropdown.vue
src/components/custom-widget-elements/Label.vue
src/components/custom-widget-elements/Slider.vue
src/components/custom-widget-elements/Switch.vue
src/components/widgets/Plotter.vue
src/libs/actions/data-lake.ts
src/libs/actions/http-request.ts
src/libs/actions/mavlink-message-actions.ts
src/libs/cosmos.ts
src/stores/omniscientLogger.ts
src/stores/widgetManager.ts
src/types/widgets.ts

We are also renaming the data-lake variables from ["CockpitActionVariable" to "DataLakeVariable"], for consistency.

Fix unlistening to data-lake variables and changing variable in the Plotter widget

---

electron/main.ts
electron/preload.ts
electron/services/storage.ts
src/components/VideoLibraryModal.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/libs/cosmos.ts
src/libs/videoStorage.ts
src/stores/video.ts
src/types/general.ts
src/types/video.ts
src/views/ConfigurationGeneralView.vue

This PR changes the behavior of the Electron-based application.
Instead of saving the video chunks, video files and telemetry logs to the IndexedDB, we now save them directly to the filesystem.
The main advantage for the user is that it stops risking losing videos on a browser cache cleanup, which was the main cause of video loss. As a side-effect, the user has also the video files directly on their machine, without the need to download them, keeping everything always organized and in sync.
https://github.com/user-attachments/assets/130f10f4-1915-4f1b-8996-f6caa8bfb25d
The implementation is done over the renderer/main IPC system, so we don't leave unnecessary filesystem permissions for the client, making everything safe.
Fix #1292.

Save videos directly to the filesystem (electron-only)

---

src/components/EditMenu.vue

not sure if red is the best color here... thoughts?

EditMenu: differentiate external widgets from Cockpit's own

---

src/views/ConfigurationLogsView.vue

Added back the telemetry frequency slider.
It used to be on a separate tab, but for vertical space saving, it was moved into a Settings expansible panel:
Solves #1515

Add telemetry frequency setting

---

src/views/ConfigurationJoystickView.vue

This was leading to a huge amount of warnings in the console (hundreds per second).

joystick-configuration-view: Remove extraneous attribute

---

src/App.vue
src/components/ConfigurationMenu.vue
src/components/development/MAVLinkInspector.vue
src/libs/connection/connection-manager.ts
src/libs/connection/connection.ts
src/libs/vehicle/ardupilot/ardupilot.ts
src/libs/vehicle/vehicle-factory.ts
src/libs/vehicle/vehicle.ts
src/stores/mainVehicle.ts
src/views/ConfigurationMAVLinkView.vue

Opening as draft as there are things to polish yet.
This tool can help on different debugging processes, like finding out what exactly Cockpit is sending as `MANUAL_CONTROL` messages, live.
https://github.com/user-attachments/assets/56f9a535-5344-4228-b13b-f98caf72d344
Fix #816.

Add MAVLink inspection tool

---

src/components/custom-widget-elements/Slider.vue
src/types/widgets.ts

- Now there is a checkbox to also apply the color to the label.
Fix  #1529

bug fix: Slider Input widget colour leaves the label white

---

src/components/InputElementConfig.vue
src/components/custom-widget-elements/Label.vue
src/types/widgets.ts

Bug Fix: "label" input widget has no way to change the text

---

electron/main.ts

In Windows and some Linux window-managers it was on the top of the window adding nothing to the application and wasting space.

electron: Auto-hide menu bar

---

src/libs/communication/mavlink.ts

This was leading to hundreds of logs per second when the vehicle was disconnected, which could lead to slowdowns in the application.
With this patch, we get 6 logs per minute at most.

mavlink: Don't log "unconnected" error too frequently

---

src/components/EditMenu.vue
src/components/mini-widgets/JoystickCommIndicator.vue
src/components/mini-widgets/MissionIdentifier.vue
src/types/widgets.ts

The end of an era...
The cursor also changes to the not-allowed type when hovering a not-configurable one.
Fix #541

edit-menu: Disable cog icon for widgets that are not configurable

---

.github/ISSUE_TEMPLATE/bugs.yml

GitHub has new [org-level Issue "types"](https://github.blog/changelog/2025-01-13-evolving-github-issues-public-preview/#organize-your-work-with-issue-types), that can help improve consistency between repositories, and adds an abstraction level so standard labels can be used for the lower level specifics instead.

.github: Issue template: bugs.yml: switch bug label to Bug type

---

src/App.vue
src/assets/defaults.ts
src/components/configuration/JavascriptActionConfig.vue
src/components/widgets/IFrame.vue

Fixes #1572 
Fixes #1560
Fixes #557

Minor fixes

---

src/components/mission-planning/ContextMenu.vue
src/components/mission-planning/ScanDirectionDial.vue
src/types/mission.ts
src/views/MissionPlanningView.vue

New Features List:
* Added a context menu for  mission planning creation and editing processes.
* Survey polygons can now be relocated by dragging them on the map.
* Surveys can be individually deleted.
* Users can select the angle at which the survey will be scanned.
* The scanning angle can also be edited after the survey is completed.
* Last survey can now be edited back to the polygon level, allowing users to adjust the distance between scan lines (scan density) and the scanning angle
* It is now possible to concatenate multiple surveys or simple paths to form a complex mission around a complex map scene
https://github.com/user-attachments/assets/e7e63da7-75b1-45e1-8a87-c76b117f303e
https://github.com/user-attachments/assets/581d9d36-352b-432e-910b-fd0b5d3f4b7f
closes #1355 
closes …

Mission Planning improvements

---

src/types/widgets.ts

widgets: Enable config menu for the DIY widget

---

src/components/VehicleDiscoveryDialog.vue
src/libs/electron/vehicle-discovery.ts

Turns out some devices like routers return 404 pages with status code 200 if you try to access inexistent subdomains of them.
Fix #1551

Do not show devices other than BlueOS vehicles in the vehicle discovery

---

src/components/configuration/HttpRequestActionConfig.vue
src/libs/actions/http-request.ts
src/libs/actions/mavlink-message-actions.ts
src/libs/utils-data-lake.ts
src/stores/mainVehicle.ts
src/views/ConfigurationGeneralView.vue

This also adds the vehicle address to the datalake. This way people can use the vehicle address in the URL, like so:
This prevents the need for editing the URL of every single action that uses the vehicle address if it changes.
Edit: also added a variable that points directly to the MAVLink2REST http endpoint:

Allow using data-lake variables in the URL of HTTP request actions

---

src/components/EditMenu.vue
src/components/widgets/CustomWidgetBase.vue
src/stores/widgetManager.ts

- ~~Added a 'double click to configure' feature to mini and regular widgets inside edit mode, so any configurable widget will have a direct way to open its config screen~~;
- Added a panel to list and edit mini-widgets inside custom mini-widgets containers;
https://github.com/user-attachments/assets/d93187f3-1b30-45ad-8804-147c2be1c6f6
Fix #1531

Add a panel to list and edit mini-widgets inside custom mini-widgets containers

---

src/stores/omniscientLogger.ts

This removes the performance logs in the console. They were generating too much noise, slowing down the application, and can't be really seen by the user when needed.
All the WebRTC stats as well as the application framerate are now data-lake variables and can be plotted/monitored when needed.

Use data lake for performance logs

---

src/App.vue
src/libs/utils.ts
src/views/ConfigurationDataLakeView.vue

Allows for monitoring of data-lake variables. 
The component is completely reactive. If new variables appear, they will be there.
I've added a fuzzy-search input so people can easily find the variables they need.
PR #1595 moves that and the MAVLink submenus to a new "Tools" category, so the current Settings menu will not take more vertical space than it should.
https://github.com/user-attachments/assets/90b71533-dc0c-4eaa-9a6e-c8e100b6f988
Fix #1451

Add Data Lake submenu

---

src/components/widgets/Plotter.vue

This prevents cases where the value is constant and no line appears in the plot, since the current and only value is equal to min and max, like when monitoring an stable video frame rate.

plotter: Adjust min and max plot heights to be a factor of the min and max values

---

src/components/widgets/Map.vue

As discussed on the issue #1550, all the bugs described there were fixed in previous pull requests related to mission planning (#1469 and #1523), but the item 4.
@JoaoMario109 pointed out a possible CSS leakage from the Map component, that indeed was the cause of the styles only being applied correctly after a page refresh. Kudos to him
Closes #1550

Prevent CSS leakage into mission planning module

---

src/views/ToolsDataLakeView.vue

Otherwise we are setting listeners to all variables in the lake, which will usually be 300+, and this will trigger a lot of unnecessary screen updates and resource usage, which can slow down the application while this menu is open.

Lazy load data lake variables in menu

---

src/components/InputElementConfig.vue

Modified the v-if filtering method to include all types of custom elements flagged by `isCustomElement`
Closes #1575

Re enable the Button's Cockpit action selector

---

src/libs/sensors-logging.ts
src/stores/video.ts

The old pipeline was saving the entire log in memory, which was affecting the application's performance.
With this new approach, there's no more logs in memory. All log points are saved in the local database, and retrieved when the request to generate the log file is made.
I took the opportunity of this refactor to also address the problem of multiple log requesters interfering with each other. Now the system will not stop logging while there's an active log requester.
Fix #1446

sensors-logging: Refactor to reduce memory usage and allow individual video subtitles

---

src/libs/joystick/protocols.ts
src/libs/joystick/protocols/data-lake.ts
src/libs/post-pinia-connections.ts
src/main.ts
src/types/joystick.ts
src/views/ConfigurationJoystickView.vue

This works for both boolean and floating buttons, so one can use trigger/bumper buttons as well.
Fix #1657

Allow setting the value of data-lake variables with joystick buttons

---

src/components/EditMenu.vue

Modified the logic that checks if the mini widgets is configurable
Closes #1662

Add input widgets to configurable mini widgets check

---

src/App.vue
src/components/Tutorial.vue
src/main.ts
src/stores/appInterface.ts
src/utils/migrations.ts

Putting on draft since I realized the stepping is broke on master. Will fix before opening it for review.
Fix #1442 
Fix #1647

Use standard key names for the settings on storage

---

src/components/widgets/Plotter.vue

It will by default add the title to existing widgets.
Fix #1667

Add title to Plotter widget

---

src/components/InputElementConfig.vue
src/stores/widgetManager.ts

- Fixed the panel closure conditions;
- Fixed the text on the Side config panel that has a incorrect reference to URL parameters;
Fixes #1663

1663 input widget configuration persists outside edit mode

---

src/components/InputElementConfig.vue
src/components/custom-widget-elements/Checkbox.vue
src/components/custom-widget-elements/Dial.vue
src/components/custom-widget-elements/Dropdown.vue
src/components/custom-widget-elements/Slider.vue
src/components/custom-widget-elements/Switch.vue

* Added an option to use an already existing data-lake variable
* Added a watch to the existing input-elements so they will update reactively on a data-lake variable bind
https://github.com/user-attachments/assets/8e761805-fee3-47af-98ea-97e19d9ef2e0
Closes #1677

Allow data-lake related input-widgets to be shared between views

---

src/App.vue
src/components/InputElementConfig.vue
src/components/Snackbar.vue
src/components/SnackbarContainer.vue
src/components/Tutorial.vue
src/components/VehicleDiscoveryDialog.vue
src/components/VideoLibraryModal.vue
src/components/widgets/CustomWidgetBase.vue
src/composables/snackbar.ts
src/stores/mainVehicle.ts
src/stores/video.ts
src/stores/widgetManager.ts
src/views/ConfigurationGeneralView.vue
src/views/MissionPlanningView.vue

- Now multiple snackbars will stack on top of each other instead of overlaying;
https://github.com/user-attachments/assets/903f5b98-e371-4ab0-a327-e93e922ed709
Closes #1227

Allow multiple snackbars to stack up on screen

---

src/components/InputElementConfig.vue

I didn't get a chance to review #1688, so here's my main suggested change.
For context, "existent" is rarely used in English, and it seems more intuitive to have buttons be verbs (since clicking a button should _do_ something) :-)

src: components: InputElementConfig.vue: clarify Action language

---

src/components/custom-widget-elements/Dial.vue

* Now the component respects the defined numerical boundaries for max and min values;
* Now the knob won't rotate past 100%, snapping back 0%;
https://github.com/user-attachments/assets/a563f0eb-831a-4a4d-b1db-f21c739e1ac2
Closes #1678

Dial: Fix rotational and numerical boundaries

---

src/components/InputElementConfig.vue
src/components/custom-widget-elements/Checkbox.vue
src/components/custom-widget-elements/Dial.vue
src/components/custom-widget-elements/Dropdown.vue
src/components/custom-widget-elements/Slider.vue
src/components/custom-widget-elements/Switch.vue

Prevent the deletion of data-lake variables when an input widget is removed

---

src/components/widgets/Plotter.vue

Fix rendering of the Plotter widget on initial states

---

src/components/configuration/ActionLinkConfig.vue
src/components/configuration/HttpRequestActionConfig.vue
src/components/configuration/MavlinkMessageActionConfig.vue
src/libs/actions/action-links.ts
src/styles/global.css
src/types/cockpit-actions.ts
src/views/ConfigurationActionsView.vue

.
To be merged after #1674
Fix #1641

Allow data-lake variables to auto trigger actions

---

src/components/configuration/CockpitSettingsManager.vue
src/types/general.ts
src/views/ConfigurationGeneralView.vue

* Users can edit, save and upload settings;
* Reset settings button will be implemented on a second approach. For now a reset for the browser storage is implemented only.
https://github.com/user-attachments/assets/ab2a4507-b1c5-4ee1-9267-2b4a132c0072
Closes #1486

Add system settings manager 

---

src/components/EditMenu.vue

* Now edit mode's left panel will display only the custom components related to the selected view.
Closes #1633

Filter custom widgets to be displayed on Edit-mode's left bar

---

src/utils/migrations.ts
src/views/WidgetsView.vue

This was causing infinite restart loops if the user tried to keep the BlueOS profiles on sync conflicts.
This solution keeps the old names in the profiles and just map them to the new names on runtime.

migration: Stop renaming old components in the profiles

---

src/components/widgets/Map.vue
src/libs/utils-map.ts
src/views/MissionPlanningView.vue

Added tooltips for all possible situations.
Fix #1736

map: Add tooltips to buttons in the widget and mission planning view

---

src/App.vue
src/stores/controller.ts
src/stores/widgetManager.ts

This patch makes sure Cockpit Actions are only called on the rising edge, so we stop spamming calls that can lead to undesired behaviors.
Fix #1670 
Fix #545

Stop spamming Cockpit Action calls (send only on the rising edge)

---

src/components/mini-widgets/BatteryIndicator.vue

- Fixed wobbly Watts symbol;
- Changed Power display text color to a very light yellow, so users can differentiate measurements more intuitively.
- Fixed NaN values when vehicle is disconnected or power module is inoperative;
https://github.com/user-attachments/assets/faf245be-787a-4cae-a9a8-fe83ad3c5a05
Closes #1668

Battery-indicator: Fix inconsistent widget width and NaN values

---

src/components/ContextMenu.vue
src/components/InputElementConfig.vue
src/components/MiniWidgetInstantiator.vue
src/components/WidgetHugger.vue
src/components/widgets/CollapsibleContainer.vue
src/directives/contextMenu.ts
src/main.ts
src/stores/widgetManager.ts
src/types/user-interface.ts

- Users can now use a right-click or a long press to open a context menu on the widgets;
- Widgets and mini widgets are now configurable outside edit-mode;
- Cockpit elements opacity can be quickly set using the context menu;
- `v-contextmenu` directive added for easy binding the context menu's triggering and opening location;
https://github.com/user-attachments/assets/fc9d4849-0fbd-4d5c-8fae-5fc39bbc510c
Closes #1610

Add quick access to widgets configs

---

src/views/ConfigurationJoystickView.vue

joystick: Filter out transforming functions from the selectable actions list

---

src/composables/settingsSyncer.ts

If an action is done behind the scenes, automatically (without user interaction), and this action is a success, we don't need to inform the user about it, we should just do it silently. 
We should only inform the user if the action is done interactively or if it fails (thus needing user attention and manual intervention).

setting-syncer: Stop opening success snackbars on startup

---

src/components/mini-widgets/VeryGenericIndicator.vue
src/components/widgets/Plotter.vue
src/libs/actions/data-lake.ts
src/libs/vehicle/ardupilot/ardupilot.ts
src/libs/vehicle/vehicle.ts
src/stores/mainVehicle.ts

With that patch, we remove the entire generic-variables system and migrate all related functionality to the data-lake system.
This means the VGI is now integrated with the data-lake system, so people can consume anything from there, as well as create their own variables (through the compound-variables/mixer system).
Main changes to watch for and test in this PR:
- Old VGIs should keep working (special attention to `NAMED_VALUE_X` stuff)
- Logging system should keep working

Deprecate generic-variables system and migrate everything to the data-lake

---

src/components/mini-widgets/MiniVideoRecorder.vue

Having a notification dot there when there is no video does not make sense, it appears that there is something and when the mouse is over it says zero.

components: MiniVideoRecorder: Do not show badge if there is no video

---

src/libs/actions/mavlink-message-actions-message-definitions.ts
src/libs/joystick/protocols/predefined-resources.ts
src/libs/vehicle/ardupilot/ardupilot.ts

This way it can be used, for example, on actions calls, without the user needing to know it in advance, or needing to replace when the vehicle is changed.
Requested by @Williangalvani based on some struggle he had configuring stuff on a mission day.

ardupilot: Add system ID to the data-lake

---

src/views/ConfigurationActionsView.vue

Replace the delete button icon from MDI's delete to MDI's trash-can-outline, and change its color to white, as the other buttons.
Those changes make it more clear that it's a trash button, and not a "stop" one, specially in low resolution screens.
Before:
After:
Fix #1831

custom-actions: Change icon and color of the delete button

---

src/libs/joystick/protocols/predefined-resources.ts

Higher frequencies can cause the autopilot to overload and delay motor commands.

predefined-resources: Enforce minimum interval of 100ms on MAVLink camera zoom/focus messages

---

src/libs/system-logging.ts
src/views/ConfigurationDevelopmentView.vue

system-logging: Sort logs by datetime in the viewing table

---

src/libs/joystick/protocols.ts

I reviewed it and actually there were several options there that simple don't make sense today.
Cockpit's joystick backend only have support today for `MANUAL_CONTROL` actions, so everything else was removed.
Fix #1900

Remove non-functional options from the joystick axis function selection

---

src/assets/defaults.ts
src/components/joysticks/JoystickCalibration.vue
src/libs/joystick/calibration.ts
src/libs/joystick/manager.ts
src/stores/controller.ts
src/types/joystick.ts
src/views/ConfigurationJoystickView.vue

This patch adds support for deadband/deadzone calibration and exponential scaling.
The deadband calibration is applied before the exponential scaling, which means the exponential curve starts as 0 in the deadband threshold.
Circle correction was still not implemented as I understand it is a less important form of calibration, and its not yet clear to me how it should be accounted for.
https://github.com/user-attachments/assets/2dfb4dd7-c3a0-492e-862c-13c42458f23f
Fix #1851 
Fix #1852

Add support for deadband calibration and exponential scaling on the joystick

---

src/App.vue
src/components/ArmSafetyDialog.vue
src/composables/armSafetyDialog.ts
src/stores/alert.ts

Added a close button as well as the ability to close the dialog it by clicking the ESC key or outside it (made it non-persistent).
Also changed the layout and texts to take less horizontal space and make it more clear what each option is going to do.
Change requested by @NickNothom.

arm-safety-menu: Make options more clear and make it easy canceling the action

---

.github/workflows/ci.yml
package.json

Notarization and signing was added to the CI so we can get the update system to work on macOS. This also comes with the benefit of not requiring the "allow insecure app" step during Cockpit installation.
This CI step was added to be run only when not in a pull-request, as fork-based PRs don't get access to repository secrets. On PRs, it will run as it was before, creating the artifacts without notarization nor signing.
The notarization and signing step [is tested and its passing](https://github.com/rafaellehmkuhl/cockpit-public/actions/runs/15075989253/job/42574582832#step:8:1) in my fork. It should be triggered as well when we merge this PR.
The test that we can do before approving is basically checking if the all the artifacts are being generated correctly and if the notarize-and-sign …

Fix auto-updates on macOS (sign and notarize the app)

---

src/views/ConfigurationJoystickView.vue

As there are bugs in the table view, the simultaneous rendering is causing unnecessary issues in the visual view.

joystick: Do not render both config tabs (visual and table) simultaneously

---

src/components/VideoLibraryModal.vue
src/stores/video.ts

They way that the processing pipeline works right now, we have 3 main things happening:
1. Video is processed (chunks merged and duration fixed)
2. Video thumbnail is generated
3. Video subtitles (telemetry) is generated
The problem that is happening is that the current video thumbnail extraction, for some reason that is still not clear, is not working for 4K videos, like the ones generated by Radcam. Those videos are also not playable in the embeded video player that we have in the video library modal.
The video is correctly processed, but as the thumbnail is failing to be generated, it is breaking the processing pipeline, causing the subtitles not to be generated, and the user to receive an error message saying the processing failed.
My solution does the following:
1. Puts the thumbnail …

video: Fix 4K video processing

---

src/components/ArmSafetyDialog.vue

I've been unwell, so missed out on reviewing #1898 before it got merged.
I think ideally there would just be one continue button, with the warning and disarming options presented as radio buttons and a checkbox respectively, e.g.:
```
⚫️ Warn me again next time                 [x] Disarm vehicle
O Don't warn me again this session
O Never warn me again                            [ CONTINUE ]
```
but I don't have the knowledge or time to do that right now, so for now I've just reordered the existing options in order of least to most "safe":

src: components: ArmSafetyDialog: improve text, reorder options

---

src/libs/vehicle/ardupilot/data-flattener.ts

data-flattener: support bitfields on mavlink data

---

src/libs/blueos.ts

The URL of the beacon status endpoint had been mistakenly altered.
Fix #1951

Fix automatic vehicle discovery

---

src/assets/joystick-profiles.ts
src/libs/joystick/manager.ts

I just want to say that the whole xbox wireless controller thing [is a f nightmare](https://www.pcgamingwiki.com/wiki/Controller:Xbox_Wireless_Controller#Technical_information).

defaults: Fix gamepad-to-cockpit-standard mapping for the Xbox One joysticks

---

package.json
src/components/VideoLibraryModal.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/components/mini-widgets/SnapshotTool.vue
src/electron/main.ts
src/electron/preload.ts
src/electron/services/workspace.ts
src/libs/cosmos.ts
src/libs/videoStorage.ts
src/stores/appInterface.ts
src/stores/snapshot.ts
src/types/shims.d.ts
src/types/snapshot.ts
src/types/widgets.ts
yarn.lock

Add a mini widget to control Cockpit snapshot capture (1). 
* Provides single and timed capture from multiple sources.
* In Electron, also provides Cockpit workspace capture.
* Add EIXF info to the image files (2)
(1)
https://github.com/user-attachments/assets/ea5ef160-9350-43df-882d-954de3df3e86
(2)

Add snapshot tool mini widget

---

src/libs/actions/data-lake.ts

- Data lake
- Updates now only notify listeners if they change the variable value 
- Actions
- Makes it more reasonable to trigger Actions from variables that are controlled by a joystick
- Joystick stability
- Fixes a bug where joystick-button data-lake variable Action triggers would trigger at the joystick update frequency, instead of only when the button value actually changes
Reduces workload when "setting" data lake variables to the value they already hold, by avoiding re-saving the value or notifying listeners that it has been updated/confirmed.
1. Raised in [this forum post](https://discuss.bluerobotics.com/t/running-multiple-mavlink-commands-with-single-button-press/20810)
1. This approach improves resource efficiency by reducing redundancy, but it's possible that could result in …

Avoid redundant data-lake updates triggering Actions

---

src/electron/main.ts
src/electron/services/memory.ts
src/electron/services/resource-monitoring.ts
src/libs/cosmos.ts
src/stores/omniscientLogger.ts

This patch adds three new data-lake variables related to resource usage on the standalone/Electron app:
- CPU usage (percentage)
- GPU memory usage (MB)
- Renderers memory usage (MB)
With them, debugging application performance becomes significantly easier.
https://github.com/user-attachments/assets/ed652c7c-d4cc-4e34-b5f2-3e5351d77f17

electron: Allow monitoring CPU usage and GPU memory

---

package.json

This patch adds the missing permissions for Cockpit to access the filesystem on Flatpak builds.
It specifically adds permission to access the `~/Cockpit` folder, which is is the only one that we use, so we don't have broadly unnecessary filesystem access.
Fixes #1891.

flatpak: Add missing filesystem permissions to fix video persistence and access

---

src/components/About.vue

Redirects work, but it's preferable to not have too many if it's avoidable.

src: components: About.vue: update old docs link

---

src/types/joystick.ts
src/views/ConfigurationJoystickView.vue

This was a performance issue that existed for a long time, but got more noticeable with the introduction of #1876 (not sure why). The application frame rate dropped a lot when entering the table tab, and for more constrained setups it got to the point of making the axis and buttons state updates to lag on several seconds.
This patch solves the problem by calculating all button states at the same time, once, every 100ms, instead of restyling the DOM for every button at the joystick rate.
Besides the performance improvement, the user should see no difference.
Before (the drop from ~60fps to ~8fps was when entering the table tab):
After (opening the table tab causes no drop in the framerate):
Fix #1435

Severely reduce the lag in the table tab of the joystick configuration page for constrained setups

---

src/electron/main.ts
src/electron/preload.ts
src/electron/services/electron-log.ts
src/libs/cosmos.ts
src/libs/system-logging.ts
src/types/electron-general.ts
src/views/ConfigurationDevelopmentView.vue

I'm opening this one in favor of #1967. I saw that the whole "electron log" vs "cockpit internal log" was causing a lot of confusion, so I decided to go for a more long-term solution.
This patch merges the Cockpit Internal logs with the Electron logs into a single file, using the same naming as the former Cockpit ones, and uses the same table as we have today to allow the user to download or delete those.
Fixes #1891.

Merge Electron logs with Cockpit internal ones

---

src/stores/mission.ts

1. Open Cockpit
2. Go to BlueOS and stop de autopilot
3. Wait for the vehicle to disconnect from Cockpit and start the autopilot again
4. The dialog should not re-appear
Fix #2009

username: Only open prompt dialog in the first vehicle connection

---

src/views/ToolsDataLakeView.vue

Considers variables with the persistent field defined to be "User variables", which allows editing their definition and deleting them. The previous approach used null-coalescing, which meant a false value for persistence was spuriously treated as an internal variable instead of a user-defined one.
Fixes #1975

data-lake table: treat non-persistent user vars correctly

---

src/components/widgets/DoItYourself.vue

Idea came from [a question in our discord channel](https://discord.com/channels/1135646343776456765/1136408531122274344/1402294749620338839).
With this, the user can have it's DIY widget in the same style as the rest of the application.
https://github.com/user-attachments/assets/75e4b927-f49a-42c9-af31-1301324b98c6

diy-widget: Allow inheriting from the Cockpit interface styles

---

.github/workflows/ci.yml

The x64 and the arm64 versions were both generating an update metadata file with the same name ("latest-mac.yml"), and since the x64 CI takes more time to complete, it was overriding the arm64 version of the file.
This PR changes the filename for the arm64 version, to use the default pattern from `electron-updater`.
It can be seen [in my fork](https://github.com/rafaellehmkuhl/cockpit-public/releases/tag/v1.16.0-beta11) that the metadata segregation is working fine.
I also took the opportunity to remove unnecessary artifacts (diffs and update metadata files) from the pull-request CI.
Fix #1988

Fix updates on macOS (arm64) 

---

src/stores/controller.ts

In some cases, with some joysticks, the left and right triggers are being parsed as `true` independently of their position.
With the default ROV profile that means one cannot control the camera tilt as both "Tilt up" and "Tilt down" are always pressed.
I could reproduce it more than once with the DualSense and [a user has reported the same with the Steam Deck in our forums](https://discuss.bluerobotics.com/t/cockpit-video-recording-on-steam-deck/20871/10).
After some investigation that was an easy fix: make it explicit in the comparison that the value to be compared is the result of the nullish coalescing operation, always.
1. Open Cockpit standalone
2. Connect your joystick
3. Connect Cockpit to a vehicle
4. Check Cockpit logs. There will be a "activeActions" list there, and the list …

controller: Cast button values to the correct type before checking for press

---

src/libs/blueos.ts
src/stores/mainVehicle.ts
src/types/blueos.ts

blueos: Add `usage` and `frequency` of each CPU core (and averages) to the data-lake

---

src/components/VideoLibraryModal.vue
src/libs/videoStorage.ts
src/stores/snapshot.ts
src/types/snapshot.ts

* Added a thumbnail folder inside ../cockpit/snapshots;
* Thumbnails are now loaded on the library, and full size pictures are lazy-loaded;
** time to open snapshot library with 1.800 pictures (1.000 in 4k): 3 seconds.
Closes #2002

Fix video library modal slowing cockpit down

---

src/libs/actions/data-lake.ts

Race conditions can cause this situation and break several components. Better to just issue a warn, as most of the time the variable would be created with the same info.
Fix #2095.

data-lake: Warn instead of throwing on creation of already existing variable

---

src/stores/snapshot.ts

At the moment the comment session is a json-ish, it would be nicer to have a real valid json to be parsed by python script ot photogrammetry software

stores: snapshot: Make comment a valid json to be parsed by software

---

src/App.vue
src/libs/joystick/protocols/cockpit-actions.ts
src/stores/snapshot.ts

This action takes a snapshot of all available streams, including the workspace (if running the standalone/electron version).
Fix #2007.

snapshot: Create dedicated action to allow taking snapshots with a button click

---

src/components/mission-planning/CommandInputForm.vue
src/components/mission-planning/WaypointConfigPanel.vue
src/components/widgets/Map.vue
src/libs/vehicle/mavlink/types.ts
src/libs/vehicle/mavlink/vehicle.ts
src/stores/mission.ts
src/types/mission.ts
src/views/MissionPlanningView.vue

Allows someone to choose one of their waypoints and change it from "Pass by" to "MAVLink Generic Waypoint". When this is done 5 new fields appear to allow the user to explicitly set the "MAV_CMD" as well as the 4 parameters.
Conversion from the vehicle to Cockpit also takes those into account (any waypoint that is not a `MAV_CMD_NAV_WAYPOINT` is casted to a "MAVLink Generic Waypoint".
In the video it can be seen that two waypoints were modified to use a MAV_CMD_DO_JUMP and skip waypoints 4 and 7 from the mission, going directly to 5 and 2, respectively.
https://github.com/user-attachments/assets/727ab4d0-c9af-44e7-893b-2f04d18bd29b
~Opening as draft as I didn't test it yet and also because I'm not completely sure about the implementation (I'm thinking about deprecating the "Pass by" and …

Add initial support for command waypoints

---

src/components/VideoLibraryModal.vue
src/stores/video.ts

The `.ass` telemetry overlays are only generated when a video is processed, so they were not being included when downloading chunks. The problem is that in such case there's no way to download those telemetry files afterwards.
Fix #2144.

video: Include telemetry overlay files when downloading raw video chunks
