bluerobotics/cockpit

src/libs/vehicle/ardupilot/ardupilot.ts

Ignore "Ok(xxx)" result messages from mavlink2rest

---

src/assets/defaults.ts

This is a proposal and should be validated internally.
Fix #537

Change default profile for the ROV

---

src/stores/widgetManager.ts

We decided to reset everyone's profile so users can see the new default ones.

Reset everyone's profiles

---

src/components/widgets/VideoPlayer.vue

Update selected IPs field when they are changed remotely in the `VideoPlayer`

---

src/components/EditMenu.vue
src/stores/widgetManager.ts

https://github.com/bluerobotics/cockpit/assets/6551040/e0450926-c0cf-4992-a368-9d7442712dbb
Fix #505

Change default layouts behavior and allow view/profile duplication

---

src/views/ConfigurationJoystickView.vue

config-joystick-view: Make modifier-key tab change consistent

---

src/components/widgets/Compass.vue
src/components/widgets/VirtualHorizon.vue

Before and after:
https://github.com/bluerobotics/cockpit/assets/6551040/a01eea58-71b8-4cfc-8fb6-62924a9b15dd
https://github.com/bluerobotics/cockpit/assets/6551040/91eae5bc-eb30-4e18-80d0-828ee0f6f889
Fix #660

Fix attitude widgets refresh

---

src/components/widgets/VideoPlayer.vue

I'm just annoyed with my flipped video when testing here.
Helps #20

video-player: Add rotation

---

src/components/mini-widgets/ArmerButton.vue

Continuing the work with issue: #673 
Interface visibility/intuition improvements
Gif with changes for review:

Change ArmerButton bgcolor when toggled

---

src/stores/widgetManager.ts

Allow configuring top right widgets

---

src/assets/defaults.ts
src/components/EditMenu.vue
src/components/mini-widgets/VeryGenericIndicator.vue
src/types/miniWidgets.ts

Fix `VeryGenericIndicator` name

---

src/assets/defaults.ts

This will align the Compass Widget to the VirtualHorizon Widget.

src: assets: default: Fix unaligned Compass Widget

---

src/components/widgets/VideoPlayer.vue
src/stores/video.ts

Fix #643 
Fix #687
To be merged after #720.

Fix small video stuff

---

src/assets/defaults.ts

Adding default profile for aerial vehicles. 
closes #682

Default MAV Profile

---

src/stores/video.ts

Remembering that the alerts automatically push to the console as well.

video: Add logs and alerts to video recording pipeline

---

src/stores/video.ts

Improve video chunks handling

---

src/stores/video.ts
src/views/ConfigurationVideoView.vue

Bug introduced yesterday on #752.

[FIX] Use temporary chunks DB instead of the recordings one on sizing and clearing

---

src/stores/video.ts

This way we don't have the case where two chunks are recorded with the same name because the counter was not updated yet.
Fix #765

video: Increase chunk counter before anything else

---

src/components/widgets/Map.vue
src/libs/utils-map.ts
src/views/MissionPlanningView.vue

Add new maps utilities for target following and add checks and better identification for current internal following target states.
Fixes #333

Fix problems related to follow home/vehicle sticking and without indication

---

src/components/mini-widgets/MiniVideoRecorder.vue
src/stores/video.ts
src/stores/widgetManager.ts
src/views/ConfigurationVideoView.vue

- Allow downloading temporary video chunks
- Fixes MiniVideoRecorder popup appearing even when not needed

Extras and fixes on the video pipeline

---

src/components/widgets/VirtualHorizon.vue

Fixes issue where virtual horizon is roll axis rotated opposite of vehicle
Also fixes issue in sim where horizon is not visible until the vehicle takes off.

Fixed Virtual Horizon Backwards

---

src/stores/video.ts

video: Stop recording counter as soon as user clicks to stop

---

src/components/SlideToConfirm.vue

slide-to-confirm: Make cancel button text unselectable

---

src/assets/defaults.ts
src/stores/widgetManager.ts

Changes prevent unconfigured veryGenericIndicators from loading in to the views on cockpit load or in profile changes
Fix #863

On profile change, unconfigured veryGenericIndicator pops and wont close

---

src/stores/alert.ts

This makes cockpit compatible with Meta Quest's browser
hint: it is a 6 lines change if you remove whitespace changes

Alert: fail nicely if TTS is not supported by browser

---

src/App.vue
src/components/Dialog.vue

Fix menu not opening after using ESC to close it

---

src/components/ConfigurationMenu.vue
src/views/ConfigurationGeneralView.vue

Those were bloating system logs and difficulting console reading.

Fix Vue warnings

---

src/components/InteractionDialog.vue
src/components/Snackbar.vue
src/components/VideoLibraryModal.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/components/widgets/VideoPlayer.vue
src/stores/video.ts
src/types/video.ts
src/views/ConfigurationVideoView.vue

Main Changes:
- Add thumbnail to unprocessed videos metadata;
- Add on demand processing routines on video store and video library;
- New component to standardize human <-> machine interactions using dialogs;
- Modify files selection logic following material design standards for multiple item selection gestures;
Closes #877

Cockpit does not offer processing of unprocessed videos

---

src/composables/webRTC.ts
src/libs/webrtc/session.ts
src/stores/video.ts
src/views/ConfigurationVideoView.vue

Allow users to choose TCP and/or UDP for ice candidate

---

src/stores/mainVehicle.ts

They can cause bad routing issues.

video: webRTC: Remove hard-coded Google stun servers

---

src/assets/defaults.ts
src/components/EditMenu.vue
src/stores/widgetManager.ts

- Fix the size of the Map widget on the MAV profile (it wasn't full-screened properly)
- Reuse the default widget construct parameters on parts of the code that were duplicating them

Fix defaults

---

src/assets/defaults.ts
src/components/EditMenu.vue
src/stores/mainVehicle.ts
src/stores/widgetManager.ts

Tie widget profiles to vehicle types and auto-change profile on boot

---

src/components/InteractionDialog.vue
src/components/VideoLibraryModal.vue

* Added a check to prevent the video library from opening while a video is being recorded.
* Added a dialog to alert the user about it;
* Modified the InteractionDialog component so it now has pre defined variants with icons and is more friendly to plain text messages.
Fix #935

One can process a video recording before stopping it

---

src/stores/video.ts

Make changes on video protocol filters reconnect current streams

---

src/libs/sensors-logging.ts

Fix bug in grid positions for the telemetry subtitle overlay

Fix subtitle overlay positioning bug

---

src/components/VideoLibraryModal.vue

Corrects a typo on the video library download dialog

Corrects dialog title text

---

src/components/widgets/Map.vue

map: Fix the URL of the vehicle images

---

src/components/EditMenu.vue
src/components/SnappingGrid.vue
src/components/WidgetHugger.vue
src/stores/widgetManager.ts
src/views/WidgetsView.vue

To be merged after #911.
Fix #846.

Get grid back

---

src/components/mini-widgets/ArmerButton.vue
src/components/mini-widgets/MiniVideoRecorder.vue
src/components/mini-widgets/TakeoffLandCommander.vue
src/libs/utils.ts
src/libs/vehicle/ardupilot/ardupilot.ts
src/libs/vehicle/types.ts
src/libs/vehicle/vehicle.ts
src/stores/mainVehicle.ts
src/views/ConfigurationJoystickView.vue

Fix promise handling, allow chaining, reduce necessity for extra parameters and improve code overall.
To be merged after #943.

Rework `COMMAND_LONG` message

---

src/components/VideoLibraryModal.vue

Updates prior to merging the Interface changes on PR #1002

Update branch with latest changes

---

src/components/VideoLibraryModal.vue

To be merged after #1017.
Fix #1006.

Disable video download button

---

src/components/mini-widgets/VeryGenericIndicator.vue

vgi: Filter out duplicated results in the variable search

---

src/views/ConfigurationVideoView.vue

Using the same UI philosophy implemented on #969  
To be merged after #1020 
Closes #971

Implement new UI to Configurations - Video

---

src/components/ExpansiblePanel.vue
src/components/GlassModal.vue
src/views/BaseConfigurationView.vue
src/views/ConfigurationLogsView.vue

Using the same UI philosophy implemented on #969

Implement new UI to Configurations - Telemetry

---

public/images/PS4.svg
src/App.vue
src/components/Button.vue
src/components/ExpansiblePanel.vue
src/components/joysticks/JoystickPS.vue
src/libs/joystick/manager.ts
src/views/ConfigurationJoystickView.vue

Adapted the current component to the new UI so it will be used until the new version #970 is ready.

Implement new UI to temporary joystick configuration module

---

src/composables/settingsSyncer.ts
src/stores/development.ts
src/views/ConfigurationDevelopmentView.vue

- Do not send alerts as they are very intrusive
- Disable sync by default (at least while Bag of Holdings [is not fixed](https://github.com/bluerobotics/BlueOS/issues/2352) to not brake on bad updates)

Changes on BlueOS settings sync

---

src/libs/connection/websocket-connection.ts
src/stores/controller.ts

Fix joystick dying if one tries to connect during boot

---

src/assets/defaults.ts
src/libs/sensors-logging.ts

Fix bad default sensors logging

---

index.html

Fix problems where the browser is still using old cached files

index: Erase browser cache with settings

---

src/views/ConfigurationLogsView.vue

Edited title to sentence case style:
Closes #1074

Title should follow other screens

---

src/views/ConfigurationLogsView.vue

Remove blindspot on checkbox

---

src/components/VideoLibraryModal.vue

Main changes:
* On screens smaller than 720p, the component will auto scale to fill about 98% the screen width;
Closes: #1034

Add responsiveness logic to the Video Library Component

---

src/stores/appInterface.ts

Good catch @rafaellehmkuhl. It did really add reactive responsiveness to the interface in a very simple way:
https://github.com/bluerobotics/cockpit/assets/14910201/9b182b72-7796-4f29-8be4-cc74475f476e

Add reactive responsiveness to the interface

---

index.html

It was throwing and preventing the clear-settings button to appear.

index: Fix missing async declaration

---

src/App.vue
src/components/widgets/Alerter.vue

alerter: Take 30% of the top bar width

---

index.html

Fix #997.
To be merged after #1084.

Change reset cockpit button

---

src/components/mini-widgets/MiniVideoRecorder.vue

mini-video-recorder: Allow opening config dialog from the edit-menu

---

src/views/ConfigurationJoystickView.vue

* Isolated the trigger that shows the warning panel/message
Closes #1070

Configuirations-joystick shows empty warning

---

src/assets/defaults.ts
src/components/widgets/IFrame.vue
src/libs/utils.ts

Confirm and validate iFrame URL before saving

---

src/components/widgets/Compass.vue

https://github.com/user-attachments/assets/675e4533-3293-4375-a2ec-3c570c662b32
Fix #1109

compass: Fix direction of rotation for the Heads up configuration

---

src/App.vue
src/stores/appInterface.ts
src/views/ConfigurationGeneralView.vue
src/views/ConfigurationUIView.vue

* Add a separated config menu item to the UI parameters;
* Auto saves user's UI parameters to BlueOS storage;

Create a config menu item for UI and allow saving the interface settings on BlueOS storage

---

src/components/mini-widgets/VeryGenericIndicator.vue

Open configured VGIs on custom tab directly

---

src/components/mini-widgets/VeryGenericIndicator.vue

Before:
After:
Fix #954
Fix #1119

Fix VGI sizing

---

src/libs/utils.ts
src/stores/mainVehicle.ts
src/stores/widgetManager.ts
src/views/ConfigurationDevelopmentView.vue
src/views/ConfigurationGeneralView.vue

Make connection URIs reactive

---

src/components/MiniWidgetContainer.vue
src/components/mini-widgets/VeryGenericIndicator.vue
src/stores/widgetManager.ts

To be merged after #1126.
Fix #1041

Allow closing the VGI by clicking outside it (or with the ESC key)

---

src/components/widgets/Attitude.vue

Before and after:
https://github.com/user-attachments/assets/e323671b-1d2f-40a2-a1c8-7f93e852c6f1

attitude-widget: Fix rotation direction for the pitch lines

---

src/components/mini-widgets/VeryGenericIndicator.vue

vgi: Fix reactivity of the available-generic-variables-names

---

src/components/widgets/Attitude.vue

attitude-widget: Render widget the first time the canvas is available

---

src/components/widgets/VideoPlayer.vue
src/libs/webrtc/session.ts

Warn about disallowed ip on widget

---

src/components/WidgetHugger.vue

widget-manager: Fix highlighting and initial auto-resizing on regular widgets

---

.github/workflows/ci.yml

ci: Fix artifacts name to follow tag and hash information

---

src/App.vue
src/components/ExpansiblePanel.vue
src/stores/alert.ts
src/stores/appInterface.ts
src/views/ConfigurationAlertsView.vue
src/views/ConfigurationDevelopmentView.vue
src/views/ConfigurationGeneralView.vue
src/views/ConfigurationJoystickView.vue
src/views/ConfigurationLogsView.vue
src/views/ConfigurationMissionView.vue
src/views/ConfigurationUIView.vue
src/views/ConfigurationVideoView.vue

@ES-Alexander gave some very nice [feedback](https://www.notion.so/Elliot-Feedback-July-9th-74d7c46ced1e4d91a11ff2acd189b84e?pvs=4) which was mostly implemented here. Some of his suggestions have generated #1177 for further implementation.
Feedback:
[fc11efae-3efc-4b3c-8653-e7e928e11014_Export-5c8020b4-272a-41b9-8fc1-625081efb9ef.zip](https://github.com/user-attachments/files/16473589/fc11efae-3efc-4b3c-8653-e7e928e11014_Export-5c8020b4-272a-41b9-8fc1-625081efb9ef.zip)
Additionally, an option was implemented in the interface-config submenu that lets the user choose between the new center-left main menu trigger (default) and the classic top-hamburger menu trigger.
fix #1142 
fix #1171

UI improvements from @ES-Alexander feedback

---

.github/workflows/ci.yml

Tested in: https://github.com/patrickelectric/cockpit-public/releases/tag/potato
Fix #1184

ci: Avoiding failing matrix fast

---

src/App.vue

ui: Fix bottom bar not toggling with cockpit-action command

---

src/components/widgets/Map.vue

Hide map buttons unless you hover/touch the widget

---

src/components/EditMenu.vue
src/types/widgets.ts

Get profile importing button back

---

src/components/mini-widgets/MiniVideoRecorder.vue

mini-video-recorder: Fix stream connection routine

---

src/App.vue
src/components/EditMenu.vue
src/components/mini-widgets/MissionIdentifier.vue

Implement small interface changes from users feedback

---

src/components/ExpansiblePanel.vue
src/views/ConfigurationJoystickView.vue

A small part of @ES-Alexander's feedback about the joystick config page

Small interface changes from @ES-Alexander feedback

---

src/App.vue
src/components/About.vue
src/components/EditMenu.vue
src/components/UserNameInputDialog.vue
src/stores/mission.ts

Main changes:
* About page now has close buttons and reopens after closing;
* Main menu trigger moved up on phone screens so it wont overlap most notches;
*  About page main menu Icon alignment on small screens;
* Username screen now has a loading state while fetching users from the vehicle;

Small adjustments before stable release

---

src/App.vue
src/components/widgets/Map.vue
src/composables/webRTC.ts
src/libs/sensors-logging.ts
src/libs/system-logging.ts
src/libs/webrtc/signaller.ts
src/stores/omniscientLogger.ts
src/stores/video.ts

Fix log overflowing

---

src/stores/video.ts

As it's the same as not choosing a preferred route.

video: Do not warn about no allowed IPs on wireless connections

---

src/libs/joystick/protocols/mavlink-manual-control.ts
src/libs/vehicle/ardupilot/ardusub.ts

This allows us to use lua scripts to control external things, such as new cameras with http requests

Add support for scripting functions in manual control

---

src/components/About.vue
src/components/UserNameInputDialog.vue

User-selection: Add logic to prevent loading loop

---

src/App.vue

* Added visual feedback to warn the user on connection loss and reestablishment.
closes #1211

Add connection-status visual feedback

---

src/views/ConfigurationJoystickView.vue

Joystick Configuration: Fix 'shift' and 'unmap' buttons logic

---

.github/workflows/ci.yml

Add arm deployments

---

src/types/genericIndicator.ts

defaults: Add VGI preset for water temperature

---

src/views/ConfigurationGeneralView.vue

webrtc: Fix "apply" button for custom configuration

---

src/libs/slide-to-confirm.ts

mission: Fix slide-to-confirm configuration not working

---

src/components/widgets/Map.vue
src/components/widgets/URLVideoPlayer.vue
src/libs/slide-to-confirm.ts
src/libs/vehicle/ardupilot/ardupilot.ts
src/stores/mainVehicle.ts
src/stores/omniscientLogger.ts

Fix #1299 
Fix #1297 
Fix #1296
Fix #1295

Fix several logs

---

src/components/widgets/Map.vue

map: Fix tooltip for home and vehicle centering buttons

---

src/components/widgets/Map.vue
src/libs/vehicle/ardupilot/ardupilot.ts
src/libs/vehicle/types.ts
src/stores/mainVehicle.ts
src/views/MissionPlanningView.vue

Fix #1294 
Fix #1300 
Fix #1304 
Fix #1306

Fix several problems in the Map usage

---

public/register_service

follow up to https://github.com/bluerobotics/BlueOS/pull/2815

register_service: allow relative paths

---

src/components/mini-widgets/BatteryIndicator.vue
src/libs/sensors-logging.ts
src/stores/mainVehicle.ts

https://github.com/user-attachments/assets/00b95fc7-fb64-4ec2-a45d-da5259f31d2c
Fix #1381 
Fix #1385

More changes bat indicator

---

src/components/ExpansiblePanel.vue
src/views/ConfigurationJoystickView.vue

https://github.com/user-attachments/assets/b816d770-d6c7-4b9c-b045-e230e2d58f23

joytick-configuration: Only show one protocol panel at a given time

---

src/components/mini-widgets/ArmerButton.vue
src/styles/global.css

unselectable class added

---

src/libs/actions/http-request.ts
src/libs/actions/mavlink-message-actions.ts

There were inconsistencies in the parsing processes.
It is now working fine.

Fix parsing of data-lake variables in the http-request and mavlink-message actions

---

src/components/widgets/Map.vue

This layers are helpful for boat missions

Add openseamap layers

---

src/assets/defaults.ts
src/stores/appInterface.ts

Changes on the default color for the UI Glass menus

App interface: Minor UI changes

---

src/components/Tutorial.vue

Disable listening for 'Enter' key outside tutorial

Tutorial: Disable conflicting key press listening

---

src/stores/widgetManager.ts

Cockpit was crashing when a custom-widget-base was added to a view.

Fix custom-widget-base instantiation problem

---

src/components/widgets/CompassHUD.vue
src/components/widgets/DepthHUD.vue

Compass and Depth HUDs: Fix background color on Mac

---

src/components/widgets/Plotter.vue
src/libs/actions/data-lake.ts

This way those listing available variables. like the Plotter widget, can always have the updated list.
Relevant to #85

data-lake: Notify consumers about updates on the list of available variables

---

src/components/EditMenu.vue

Fix mini-widgets selecting bug

---

package.json

Daniel tested on Windows and stated that it's working fine!

electron: Allow user to choose installation folder on Windows

---

src/components/Tutorial.vue

This improves the language of the existing stages, but doesn't add new steps for the MAVLink inspector or custom actions sections, and has some issues with the tutorial window not vertically stretching to fit the content 🤷‍♂️

Tutorial: text improvements

---

src/components/EditMenu.vue

Uses Kelp Green as a more consistent accent colour in Edit Mode:
Fixes #1586

src: components: EditMenu.vue: apply kelp green consistently

---

src/views/ConfigurationActionsView.vue

https://github.com/user-attachments/assets/55f8c4a8-b505-49c3-a4a1-7ff68e7a0ad6
Helps with #1573

custom-actions: Allow sorting configuration table by name or type

---

src/assets/joystick-profiles.ts

Too many people have suffered already...

joystick: Remove "roll pitch toggle" from default ROV mapping

---

src/components/custom-widget-elements/Checkbox.vue
src/components/custom-widget-elements/Dial.vue
src/components/custom-widget-elements/Dropdown.vue
src/components/custom-widget-elements/Slider.vue
src/components/custom-widget-elements/Switch.vue

Fix input widgets disappearing between restart or clone

---

src/components/widgets/Plotter.vue

Fix position of the title background in the Plotter widget

---

src/components/custom-widget-elements/Dial.vue

**To be merged before #1715** 
* User now rotates the mouse around the knob to change its value;
* User can input the value manually (on Show Value mode);
* User can step up/down the value (Show Value mode);
* Alert on max value smaller than min value;
Uploading Screenshare - 2025-02-25 7_30_42 AM.mp4…

Improve UX and value input method on Dial component

---

src/types/genericIndicator.ts

very-generic-indicator: Add "Altitude" preset (based on rangefinder)

---

src/components/custom-widget-elements/Dial.vue

Fixed: Dial increment/decrement don't update the data lake

---

src/libs/actions/free-javascript.ts
src/libs/actions/http-request.ts
src/libs/actions/mavlink-message-actions.ts
src/libs/joystick/protocols/predefined-resources.ts
src/libs/utils.ts
src/main.ts

Testing this PR should be simple:
1. Open Cockpit
2. Connect a Joystick
3. Assign the `camera-zoom-decrease`, `camera-zoom-increase`, `camera-focus-decrease` and `camera-focus-increase` to the bumpers (L2/R2)
4. Open the `mavlink-server` UI
5. Search for "command" in the serch input
6. Click the bumpers and watch for `COMMAND_LONG` messages with the param2 going from -1 to +1
Fix #1732

Add necessary resources for enabling camera Zoom and Focus through MAVLink

---

src/components/widgets/DoItYourself.vue

DIY widget: Allow exporting and importing configuration

---

src/components/InputElementConfig.vue
src/components/custom-widget-elements/Dial.vue

Fix: deleting min max value breaks Dial input component

---

src/stores/widgetManager.ts

Add top-bar as valid container for input widgets

---

src/components/DataLakeVariableDialog.vue
src/libs/actions/data-lake.ts
src/views/ToolsDataLakeView.vue

https://github.com/user-attachments/assets/67fc336f-64e9-48f7-9c2f-94a15e93353c
Fix #1743

data-lake: Allow user to create persistent custom variables

---

src/libs/joystick/protocols/data-lake.ts

joystick: Get data-lake injected values back to zero if button+modifier not being pressed

---

src/libs/actions/action-links.ts

This prevents situations where the data-lake variable was updated in the middle of the delay, and the last known value never triggers the action.

cockpit-actions: Send the last variable value on action-links after timeout is reached

---

src/components/widgets/Plotter.vue

Uses the same mechanism that we have in the Action Links configuration dialog:
https://github.com/user-attachments/assets/1c267922-1b60-4227-90b7-6829abaacfc9
Fix #1776

plotter: Add search input to make it easier finding variables

---

src/components/development/MAVLinkInspector.vue

mavlink-inspector: Add timestamp of the incoming/outgoing messages

---

src/components/configuration/ActionLinkConfig.vue
src/libs/actions/auto-run.ts
src/main.ts

https://github.com/user-attachments/assets/98ec7444-735f-45ba-9bfb-b23109709528

cockpit-actions: Allow auto-running once or on intervals

---

src/views/ConfigurationJoystickView.vue

joystick-config: Do not toggle the layout if a modifier key is phisically pressed

---

src/components/widgets/Map.vue
src/views/MissionPlanningView.vue

Maps: Allow higher non-native zoom levels

---

src/components/joysticks/AxisVisualization.vue
src/views/ConfigurationJoystickView.vue

Before:
https://github.com/user-attachments/assets/01af3d06-733e-40c1-ac3c-8523423a55ef
After:
https://github.com/user-attachments/assets/905db4b2-1916-4f08-8b3d-820d0cf6df51
Fix #1614

Fix preview values of joystick axis in the configuration page

---

src/components/configuration/HttpRequestActionConfig.vue

http-actions: Change color of the create button to reflect our standard

---

src/components/DataLakeVariableDialog.vue
src/components/InputElementConfig.vue
src/components/custom-widget-elements/Checkbox.vue
src/components/custom-widget-elements/Dial.vue
src/components/custom-widget-elements/Slider.vue
src/components/custom-widget-elements/Switch.vue
src/libs/actions/data-lake-transformations.ts
src/libs/actions/data-lake.ts
src/libs/joystick/protocols/predefined-resources.ts
src/libs/vehicle/ardupilot/ardupilot.ts
src/libs/vehicle/ardupilot/data-flattener.ts
src/stores/mainVehicle.ts
src/stores/omniscientLogger.ts
src/views/ConfigurationJoystickView.vue

joystick: Do not show system variables in the mapping options

---

src/components/development/MAVLinkInspector.vue

https://github.com/user-attachments/assets/ba19584e-d157-4592-9e3d-b359445016bb

mavlink-inspector: Allow easily untracking messages

---

src/components/InputElementConfig.vue
src/components/custom-widget-elements/Button.vue

Fixes #1535 - not just Custom HTTP Actions anymore 😅 
https://github.com/user-attachments/assets/65b271bb-4c82-42e4-abe8-b0f2840d6083

src: components: input-widgets: button: allow all Actions

---

src/views/ConfigurationJoystickView.vue

https://github.com/user-attachments/assets/a7dcc7b3-fd62-419f-b36e-996f25574862
Fix #1870

Fix joystick mapping menu

---

src/components/UserNameInputDialog.vue
src/composables/settingsSyncer.ts
src/libs/blueos.ts
src/libs/electron/vehicle-discovery.ts
src/stores/mainVehicle.ts
src/views/ConfigurationGeneralView.vue

* Added a context-menu option to delete a user from the list.
* The currently selected user is highlighted in the list and cannot be deleted.
Additional improvements:
* Pressing Enter after typing a new username now saves it—no mouse needed.
* Moved vehicle information fetching functions to blueos.ts lib;
https://github.com/user-attachments/assets/aadf6e9e-cbc0-4003-afe0-ed7bd16bea3d
Closes #1802

Add option to delete users from BlueOS

---

src/stores/controller.ts

This way the user always have the most up to date mapping available, and we can fix previously wrong values.
Fix #1827

joystick: mapping: Always use standard mapping from our database if available

---

src/components/mini-widgets/Clock.vue

I feel like a boomer uploading a physically-recorded screencast.
https://github.com/user-attachments/assets/187d61c4-1908-4062-a9ba-5f24b8e5b410
Fix #1888

clock: Fix overflowing on Steam Deck

---

src/libs/blueos.ts

Yeah, shame on me.
I tested the build now to make sure.

electron: blueos: Add missing colon in the protocol

---

src/libs/joystick/protocols/cockpit-actions.ts
src/stores/video.ts

Asked by Wilson, to reduce the number of necessary buttons in the default joystick profile.

Add recording toggle functionality

---

src/App.vue
src/components/MainMenu.vue
src/components/SkullAnimation.vue
src/stores/appInterface.ts
src/views/ConfigurationGeneralView.vue

https://github.com/user-attachments/assets/d1b121fc-2091-41e2-a8ad-b93b60dbe771

pirate-mode: Add initial implementation

---

src/components/MainMenu.vue
src/libs/utils.ts
src/libs/vehicle/ardupilot/ardupilot.ts
src/libs/vehicle/ardupilot/defaults.ts
src/libs/vehicle/ardupilot/types.ts
src/stores/appInterface.ts
src/stores/mainVehicle.ts
src/views/ConfigurationMAVLinkView.vue

https://github.com/user-attachments/assets/95d3d2f6-e855-4f7a-b15e-1096f06bf85f
To be merged after #1912 
Fix #1857

mavlink: Allow setting the frequency requested for individual messages

---

src/libs/blueos.ts

Happens when error it fails to fetch

libs: blueos: Fix error when there is no connection to bag of holding

---

index.html
src/libs/index-utils.js

This change in the text cover a very common case when using Cockpit as a BlueOS extension, preventing unnecessary loss of settings.
@ES-Alexander let me know if you have any idea on how to improve this text.

underlying-fallback: Improve text to suggest hard-resetting

---

src/components/mini-widgets/EkfStateIndicator.vue
src/types/widgets.ts

| Name | Description | Purpose | Sources | Future |
|---|---|---|---|---|
| EKF Status Tracking | New mini-widget tracking the autopilot's EKF status, with details in a pop-up | Debugging / understanding vehicle issues | - Depends on/includes #1947<br>- Uses thresholds from the [Mission Planner EKF status popup](https://ardupilot.org/copter/docs/ekf-inav-failsafe.html) | "Mini-widget with dynamic colour and icon" could be extracted into a component, as part of the ViewDo widget suggested in #1868 (or similar) |

Ekf status

---

src/components/mini-widgets/MiniVideoRecorder.vue

widgets: mini-video-recorder: Fix connection on stream select

---

src/views/ConfigurationJoystickView.vue

- Joystick mapping
- Fixes #1804
- Closes #1261 (as the new intended behaviour)

Allow unknown joysticks to use visual config

---

src/composables/settingsSyncer.ts

To be merged after #1973.
Fix #1972

Fix blueos username log

---

src/libs/vehicle/ardupilot/data-flattener.ts

data-lake: ardupilot: data-flattener: Include ID on messages that have it

---

src/libs/vehicle/ardupilot/ardupilot.ts

A mission should always be downloadable now, even if it takes time. They only case where a download will fail is when the 10s timeout between ping-pongs is reached, which should not happen, even on very constrained situations.
- Remove the global upload timeout
- Add timeout between ping-pongs
- Add comprehensive debugging logs
- Remove unnecessary checks
Fix #2040 
Fix #2048

Make downloading of Ardupilot missions 100% reliable

---

src/libs/actions/http-request.ts

HTTP Actions: Allow query params in the URL field

---

src/components/configuration/HttpRequestActionConfig.vue
src/electron/main.ts
src/electron/preload.ts
src/electron/services/user-agent.ts
src/libs/actions/http-request.ts
src/libs/cosmos.ts

This allow Cockpit to interface with APIs that require specific user-agents to be calling.
Fix #2087.
To be merged after #2090.

actions: http: Allow settings custom user agent

---

src/components/custom-widget-elements/Slider.vue

Fix #2096.
To be merged after #2097.

input-widgets: slider: Fix switching variables and external variable tracking

---

src/stores/mainVehicle.ts
src/views/ConfigurationGeneralView.vue

If a wrong URL is applied it breaks the entire main menu

Avoid WebRTCURI configuration to break main interface

---

src/views/ConfigurationGeneralView.vue

This avoids applying wrong URLs

views: ConfigurationGeneralView: Disable apply button if configuration is invalid

---

src/views/MissionPlanningView.vue

Also adds a tooltip to the button.
Fix #2149.

Fix tile-downloading button being over the waypoint config menu

---

package.json
yarn.lock

This will be needed for other PRs, including #2164, as without the downgrade and the resolution rule, the natural resolution gets it into a version that is not compatible with the rest of the packages.

Fix strip ansi resolution
